import type { Puzzle } from './types';

/**
 * Curated "famous blunders" puzzle set — the guest / no-account library.
 *
 * Each puzzle is the critical position from a famous master game where the
 * side to move has a forced win. The solver plays the hero's side and must
 * find the key move.
 *
 * The first 7 are hand-authored icons (Morphy's Opera Game, the
 * Immortal Game, Fischer's "Game of the Century", the Légal Trap, …). The rest
 * were generated from public-domain PgnMentor game collections of famous
 * players: a solver scans each game that ended in checkmate for the position
 * where the winner has a *unique forced mate in 2–3*, and that becomes the
 * puzzle. Every setup / best / mistake sequence here is replayed through
 * chess.js for legality, the side-to-move matches `abdulsColor`, and the
 * `bestMove` SAN is chess.js's canonical form so it compares exactly against
 * the move the user makes on the board. Underpromotion mates are excluded
 * because the board UI can't input them.
 *
 * Eval numbers are illustrative, not Stockfish output: `±99` renders as
 * "+M" / "−M" to flag a forced mate; `evalAfter` is roughly where the
 * position slips if the star move is missed.
 *
 * Regenerate with build-famous.mjs (not shipped).
 */

export const FAMOUS_PUZZLES: Puzzle[] = [
  {
    "id": "famous_opera_1858",
    "gameId": "famous-opera-1858",
    "site": "https://en.wikipedia.org/wiki/Opera_Game",
    "player": "Paul Morphy",
    "opponent": "Duke of Brunswick & Count Isouard",
    "eco": "C41",
    "date": "1858",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "d6",
      "d4",
      "Bg4",
      "dxe5",
      "Bxf3",
      "Qxf3",
      "dxe5",
      "Bc4",
      "Nf6",
      "Qb3",
      "Qe7",
      "Nc3",
      "c6",
      "Bg5",
      "b5",
      "Nxb5",
      "cxb5",
      "Bxb5+",
      "Nbd7",
      "O-O-O",
      "Rd8",
      "Rxd7",
      "Rxd7",
      "Rd1",
      "Qe6",
      "Bxd7+",
      "Nxd7"
    ],
    "bestMove": "Qb8+",
    "mistakeMove": "Qxe6+",
    "evalBefore": 99,
    "evalAfter": 2,
    "drop": 7,
    "type": "blunder"
  },
  {
    "id": "famous_reti_tartakower_1910",
    "gameId": "famous-reti-tartakower-1910",
    "site": "https://en.wikipedia.org/wiki/Richard_R%C3%A9ti",
    "player": "Richard Réti",
    "opponent": "Savielly Tartakower",
    "eco": "B15",
    "date": "1910",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "c6",
      "d4",
      "d5",
      "Nc3",
      "dxe4",
      "Nxe4",
      "Nf6",
      "Qd3",
      "e5",
      "dxe5",
      "Qa5+",
      "Bd2",
      "Qxe5",
      "O-O-O",
      "Nxe4"
    ],
    "bestMove": "Qd8+",
    "mistakeMove": "Qxe4",
    "evalBefore": 99,
    "evalAfter": 1.5,
    "drop": 7.5,
    "type": "blunder"
  },
  {
    "id": "famous_lasker_thomas_1912",
    "gameId": "famous-lasker-thomas-1912",
    "site": "https://en.wikipedia.org/wiki/Edward_Lasker",
    "player": "Edward Lasker",
    "opponent": "George Thomas",
    "eco": "A84",
    "date": "1912",
    "abdulsColor": "white",
    "setupMoves": [
      "d4",
      "e6",
      "Nf3",
      "f5",
      "Nc3",
      "Nf6",
      "Bg5",
      "Be7",
      "Bxf6",
      "Bxf6",
      "e4",
      "fxe4",
      "Nxe4",
      "b6",
      "Ne5",
      "O-O",
      "Bd3",
      "Bb7",
      "Qh5",
      "Qe7"
    ],
    "bestMove": "Qxh7+",
    "mistakeMove": "Nxf6+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 8,
    "type": "blunder"
  },
  {
    "id": "famous_legal_1750",
    "gameId": "famous-legal-1750",
    "site": "https://en.wikipedia.org/wiki/L%C3%A9gal_Trap",
    "player": "Sire de Légal",
    "opponent": "Saint Brie",
    "eco": "C50",
    "date": "1750",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "d6",
      "Nc3",
      "Bg4"
    ],
    "bestMove": "Nxe5",
    "mistakeMove": "h3",
    "evalBefore": 4,
    "evalAfter": 0.3,
    "drop": 3.7,
    "type": "blunder"
  },
  {
    "id": "famous_canal_peruvian_1934",
    "gameId": "famous-canal-1934",
    "site": "https://en.wikipedia.org/wiki/Esteban_Canal",
    "player": "Esteban Canal",
    "opponent": "Amateur",
    "eco": "B15",
    "date": "1934",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "c6",
      "d4",
      "d5",
      "Nc3",
      "dxe4",
      "Nxe4",
      "Nd7",
      "Qe2",
      "Ngf6"
    ],
    "bestMove": "Nd6#",
    "mistakeMove": "Nxf6+",
    "evalBefore": 99,
    "evalAfter": 2.5,
    "drop": 6,
    "type": "blunder"
  },
  {
    "id": "famous_byrne_fischer_1956",
    "gameId": "famous-byrne-fischer-1956",
    "site": "https://en.wikipedia.org/wiki/The_Game_of_the_Century_(chess)",
    "player": "Bobby Fischer",
    "opponent": "Donald Byrne",
    "eco": "D92",
    "date": "1956",
    "abdulsColor": "black",
    "setupMoves": [
      "Nf3",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "d4",
      "O-O",
      "Bf4",
      "d5",
      "Qb3",
      "dxc4",
      "Qxc4",
      "c6",
      "e4",
      "Nbd7",
      "Rd1",
      "Nb6",
      "Qc5",
      "Bg4",
      "Bg5",
      "Na4",
      "Qa3",
      "Nxc3",
      "bxc3",
      "Nxe4",
      "Bxe7",
      "Qb6",
      "Bc4",
      "Nxc3",
      "Bc5",
      "Rfe8+",
      "Kf1"
    ],
    "bestMove": "Be6",
    "mistakeMove": "Nxd1",
    "evalBefore": -3.5,
    "evalAfter": -1,
    "drop": 2.5,
    "type": "blunder"
  },
  {
    "id": "famous_immortal_1851",
    "gameId": "famous-immortal-1851",
    "site": "https://en.wikipedia.org/wiki/Immortal_Game",
    "player": "Adolf Anderssen",
    "opponent": "Lionel Kieseritzky",
    "eco": "C33",
    "date": "1851",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Bc4",
      "Qh4+",
      "Kf1",
      "b5",
      "Bxb5",
      "Nf6",
      "Nf3",
      "Qh6",
      "d3",
      "Nh5",
      "Nh4",
      "Qg5",
      "Nf5",
      "c6",
      "g4",
      "Nf6",
      "Rg1",
      "cxb5",
      "h4",
      "Qg6",
      "h5",
      "Qg5",
      "Qf3",
      "Ng8",
      "Bxf4",
      "Qf6",
      "Nc3",
      "Bc5",
      "Nd5",
      "Qxb2",
      "Bd6",
      "Bxg1",
      "e5",
      "Qxa1+",
      "Ke2",
      "Na6",
      "Nxg7+",
      "Kd8",
      "Qf6+",
      "Nxf6"
    ],
    "bestMove": "Be7#",
    "mistakeMove": "exf6",
    "evalBefore": 99,
    "evalAfter": 3,
    "drop": 6,
    "type": "blunder"
  },
  {
    "id": "famous_morphy_morphy-paul_nn_28",
    "gameId": "famous-morphy-paul-nn-1858",
    "site": "https://lichess.org/analysis/r4b1r/ppp3pp/4Q3/4p3/2Pqk3/8/PP1P1PPP/R1B1K2R_w_KQ_-_1_15",
    "player": "Paul Morphy",
    "opponent": "NN",
    "eco": "C57",
    "date": "1858",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Nf6",
      "Ng5",
      "d5",
      "exd5",
      "Nxd5",
      "Nxf7",
      "Kxf7",
      "Qf3+",
      "Ke6",
      "Nc3",
      "Nd4",
      "Bxd5+",
      "Kd6",
      "Qf7",
      "Be6",
      "Bxe6",
      "Nxe6",
      "Ne4+",
      "Kd5",
      "c4+",
      "Kxe4",
      "Qxe6",
      "Qd4"
    ],
    "bestMove": "Qg4+",
    "mistakeMove": "Qxe5+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_morphy_morphy-paul_dominguez_34",
    "gameId": "famous-morphy-paul-dominguez-1864",
    "site": "https://lichess.org/analysis/r1bq1r2/pp1kn2p/2pN2p1/3BQ3/3p4/8/PPP2PPP/R3R1K1_w_-_-_1_18",
    "player": "Paul Morphy",
    "opponent": "Dominguez",
    "eco": "C55",
    "date": "1864",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d4",
      "exd4",
      "O-O",
      "Bc5",
      "e5",
      "Ne4",
      "Bd5",
      "f5",
      "exf6",
      "Nxf6",
      "Bg5",
      "Be7",
      "Bxf6",
      "Bxf6",
      "Re1+",
      "Ne7",
      "Ne5",
      "Bxe5",
      "Qh5+",
      "g6",
      "Qxe5",
      "Rf8",
      "Nd2",
      "c6",
      "Ne4",
      "d6",
      "Nxd6+",
      "Kd7"
    ],
    "bestMove": "Be6+",
    "mistakeMove": "Nxc8",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_morphy_morphy-paul_nn_40",
    "gameId": "famous-morphy-paul-nn-1858",
    "site": "https://lichess.org/analysis/r1bqr3/ppp3pp/8/3B4/k7/2Q5/P1P2PPP/4R1K1_w_-_-_1_21",
    "player": "Paul Morphy",
    "opponent": "NN",
    "eco": "C55",
    "date": "1858",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d4",
      "exd4",
      "Ng5",
      "d5",
      "exd5",
      "Nxd5",
      "O-O",
      "Be7",
      "Nxf7",
      "Kxf7",
      "Qf3+",
      "Ke6",
      "Nc3",
      "dxc3",
      "Re1+",
      "Ne5",
      "Bf4",
      "Bf6",
      "Bxe5",
      "Bxe5",
      "Rxe5+",
      "Kxe5",
      "Re1+",
      "Kd4",
      "Bxd5",
      "Re8",
      "Qd3+",
      "Kc5",
      "b4+",
      "Kxb4",
      "Qd4+",
      "Ka5",
      "Qxc3+",
      "Ka4"
    ],
    "bestMove": "Qb3+",
    "mistakeMove": "Rxe8",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_morphy_morphy-paul_jefferson-bt_40",
    "gameId": "famous-morphy-paul-jefferson-bt-1859",
    "site": "https://lichess.org/analysis/r4k1r/p1p1Nppp/1b2b3/4P3/6qP/Q1P5/P4PP1/RN3RK1_w_-_-_5_21",
    "player": "Paul Morphy",
    "opponent": "BT. Jefferson",
    "eco": "C52",
    "date": "1859",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "b4",
      "Bxb4",
      "c3",
      "Bc5",
      "O-O",
      "d6",
      "d4",
      "Bb6",
      "dxe5",
      "dxe5",
      "Qb3",
      "Qf6",
      "Bb5",
      "Be6",
      "Qa4",
      "Ne7",
      "Bg5",
      "Qg6",
      "Bxe7",
      "Kxe7",
      "Bxc6",
      "bxc6",
      "Nxe5",
      "Qf6",
      "Nxc6+",
      "Kf8",
      "e5",
      "Qg5",
      "h4",
      "Qg4",
      "Qa3+",
      "Kg8",
      "Ne7+",
      "Kf8"
    ],
    "bestMove": "Ng6+",
    "mistakeMove": "Qxa7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_morphy_mac-connel-james_morphy-paul_41",
    "gameId": "famous-mac-connel-james-morphy-paul-1849",
    "site": "https://lichess.org/analysis/r4rk1/p7/1q2b2p/3p1pp1/2P2p2/8/PPQN1nPP/R1B2RK1_b_-_-_2_21",
    "player": "Paul Morphy",
    "opponent": "James Mac Connel",
    "eco": "C38",
    "date": "1849",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "Bc4",
      "Bg7",
      "d3",
      "h6",
      "O-O",
      "Nf6",
      "c3",
      "b5",
      "Bxb5",
      "c6",
      "Bc4",
      "d5",
      "exd5",
      "cxd5",
      "Qe2+",
      "Be6",
      "Bb3",
      "O-O",
      "d4",
      "Ne4",
      "Bc2",
      "f5",
      "Nbd2",
      "Nc6",
      "c4",
      "Bxd4+",
      "Nxd4",
      "Nxd4",
      "Qd3",
      "Qb6",
      "Kh1",
      "Nxc2",
      "Qxc2",
      "Nf2+",
      "Kg1"
    ],
    "bestMove": "Nh3+",
    "mistakeMove": "Qxb2",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_morphy_morphy-paul_morphy-ernest_44",
    "gameId": "famous-morphy-paul-morphy-ernest-1850",
    "site": "https://lichess.org/analysis/1R1rk2r/p1R2ppp/2q4n/4p3/8/B4N2/P4PPP/6K1_w_-_-_0_23",
    "player": "Paul Morphy",
    "opponent": "Ernest Morphy",
    "eco": "C52",
    "date": "1850",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "b4",
      "Bxb4",
      "c3",
      "Ba5",
      "d4",
      "exd4",
      "O-O",
      "Bxc3",
      "Nxc3",
      "dxc3",
      "Ba3",
      "d6",
      "Qb3",
      "Nh6",
      "Qxc3",
      "Qf6",
      "e5",
      "dxe5",
      "Rfe1",
      "Bd7",
      "Rab1",
      "O-O-O",
      "Ba6",
      "Na5",
      "Rec1",
      "Bc6",
      "Qxa5",
      "bxa6",
      "Qxa6+",
      "Kd7",
      "Rxc6",
      "Qf5",
      "Rxc7+",
      "Ke8",
      "Qc6+",
      "Qd7",
      "Rb8",
      "Qxc6"
    ],
    "bestMove": "Re7+",
    "mistakeMove": "Rxc6",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_anderssen_harrwitz-daniel_anderssen-adolf_28",
    "gameId": "famous-harrwitz-daniel-anderssen-adolf-1848",
    "site": "https://lichess.org/analysis/rnbq1rk1/pppp3p/1b6/3NN1pQ/2BP4/6p1/PPP4P/R4K1R_w_-_-_0_15",
    "player": "Daniel Harrwitz",
    "opponent": "Adolf Anderssen",
    "eco": "C33",
    "date": "1848",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Bc4",
      "Qh4+",
      "Kf1",
      "Bc5",
      "d4",
      "Bb6",
      "Nf3",
      "Qe7",
      "Nc3",
      "Nf6",
      "e5",
      "Nh5",
      "Nd5",
      "Qd8",
      "g4",
      "fxg3",
      "Bg5",
      "f6",
      "exf6",
      "gxf6",
      "Ne5",
      "O-O",
      "Qxh5",
      "fxg5+"
    ],
    "bestMove": "Nf6+",
    "mistakeMove": "Nf4+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_anderssen_kloos-h_anderssen-adolf_33",
    "gameId": "famous-kloos-h-anderssen-adolf-1861",
    "site": "https://lichess.org/analysis/r3k3/ppp2p2/1bnp3p/4p3/2B1n3/P2PBPq1/1PP5/R2Q1R1K_b_q_-_1_17",
    "player": "Adolf Anderssen",
    "opponent": "H. Kloos",
    "eco": "C50",
    "date": "1861",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Bc4",
      "Nf6",
      "Nc3",
      "Bc5",
      "Nf3",
      "Nc6",
      "d3",
      "d6",
      "h3",
      "h6",
      "a3",
      "Bb6",
      "O-O",
      "g5",
      "Be3",
      "g4",
      "hxg4",
      "Bxg4",
      "Ne2",
      "Bxf3",
      "gxf3",
      "Rg8+",
      "Kh1",
      "Nxe4",
      "Ng3",
      "Qh4+",
      "Kg2",
      "Rxg3+",
      "fxg3",
      "Qxg3+",
      "Kh1"
    ],
    "bestMove": "Qh3+",
    "mistakeMove": "Bxe3",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_anderssen_anderssen-adolf_suhle-berthold_40",
    "gameId": "famous-anderssen-adolf-suhle-berthold-1859",
    "site": "https://lichess.org/analysis/2rq1r1k/pp3pRp/1b1p4/3p4/2n1P3/3B1P2/PB2NP1P/R6K_w_-_-_1_21",
    "player": "Adolf Anderssen",
    "opponent": "Berthold Suhle",
    "eco": "C51",
    "date": "1859",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "b4",
      "Bxb4",
      "c3",
      "Bc5",
      "O-O",
      "d6",
      "d4",
      "exd4",
      "cxd4",
      "Bb6",
      "d5",
      "Na5",
      "Bb2",
      "Nf6",
      "Bd3",
      "Bg4",
      "Nc3",
      "c6",
      "Ne2",
      "O-O",
      "Qd2",
      "Rc8",
      "Qg5",
      "Bxf3",
      "gxf3",
      "cxd5",
      "Kh1",
      "Nc4",
      "Rg1",
      "Ne8",
      "Qxg7+",
      "Nxg7",
      "Rxg7+",
      "Kh8"
    ],
    "bestMove": "Rg8+",
    "mistakeMove": "Bxc4",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_anderssen_anderssen-adolf_nn_40",
    "gameId": "famous-anderssen-adolf-nn-1861",
    "site": "https://lichess.org/analysis/r4rk1/1pp2ppp/1p1p4/n2P4/4P3/3n4/PB3PRP/R6K_w_-_-_0_21",
    "player": "Adolf Anderssen",
    "opponent": "NN",
    "eco": "C51",
    "date": "1861",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "b4",
      "Bxb4",
      "c3",
      "Bc5",
      "O-O",
      "d6",
      "d4",
      "exd4",
      "cxd4",
      "Bb6",
      "d5",
      "Na5",
      "Bb2",
      "Nf6",
      "Bd3",
      "O-O",
      "Nc3",
      "Bg4",
      "Na4",
      "Nd7",
      "Nxb6",
      "axb6",
      "Qc2",
      "Bxf3",
      "gxf3",
      "Ne5",
      "Kh1",
      "Qf6",
      "Rg1",
      "Qxf3+",
      "Rg2",
      "Qxd3",
      "Qxd3",
      "Nxd3"
    ],
    "bestMove": "Rxg7+",
    "mistakeMove": "Bxg7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_anderssen_nn_anderssen-adolf_41",
    "gameId": "famous-nn-anderssen-adolf-1861",
    "site": "https://lichess.org/analysis/2k3r1/ppp2pr1/2n4p/2P1p3/4n3/2PBBqP1/PP3P2/3R1RK1_b_-_-_0_21",
    "player": "Adolf Anderssen",
    "opponent": "NN",
    "eco": "C50",
    "date": "1861",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "O-O",
      "Nf6",
      "d3",
      "d6",
      "Nc3",
      "h6",
      "h3",
      "g5",
      "Na4",
      "g4",
      "hxg4",
      "Bxg4",
      "Nxc5",
      "dxc5",
      "c3",
      "Qd6",
      "Be3",
      "O-O-O",
      "Qe2",
      "Rdg8",
      "Rad1",
      "Rg7",
      "Kh1",
      "Rhg8",
      "d4",
      "Nxe4",
      "dxc5",
      "Qg6",
      "Bd3",
      "Qh5+",
      "Kg1",
      "Bxf3",
      "Qxf3",
      "Qxf3",
      "g3"
    ],
    "bestMove": "Rxg3+",
    "mistakeMove": "Qxd1",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_tal_tal-mihail_stean-michael_62",
    "gameId": "famous-tal-mihail-stean-michael-1973",
    "site": "https://lichess.org/analysis/1q5r/1b5p/8/r4pQ1/8/2N5/PPP3Pk/1K3R2_w_-_-_6_32",
    "player": "Mihail Tal",
    "opponent": "Michael Stean",
    "eco": "B96",
    "date": "1973",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "c5",
      "Nf3",
      "d6",
      "d4",
      "cxd4",
      "Nxd4",
      "Nf6",
      "Nc3",
      "a6",
      "Bg5",
      "e6",
      "f4",
      "Nbd7",
      "Qf3",
      "Qc7",
      "O-O-O",
      "b5",
      "Bxb5",
      "axb5",
      "Ndxb5",
      "Qb8",
      "e5",
      "Bb7",
      "Qe2",
      "dxe5",
      "Qc4",
      "Bc5",
      "Bxf6",
      "gxf6",
      "Rxd7",
      "Be3+",
      "Kb1",
      "Kxd7",
      "Rd1+",
      "Bd4",
      "fxe5",
      "fxe5",
      "Nxd4",
      "exd4",
      "Qxd4+",
      "Ke7",
      "Qc5+",
      "Kf6",
      "Rf1+",
      "Kg6",
      "Qe7",
      "f5",
      "Qxe6+",
      "Kg7",
      "Qe7+",
      "Kg6",
      "h4",
      "Ra5",
      "h5+",
      "Kxh5",
      "Qf7+",
      "Kh4",
      "Qf6+",
      "Kg3",
      "Qg5+",
      "Kh2"
    ],
    "bestMove": "Qh4+",
    "mistakeMove": "Qxf5",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_tal_ostrauskas-a_tal-mihail_73",
    "gameId": "famous-ostrauskas-a-tal-mihail-1955",
    "site": "https://lichess.org/analysis/7k/6pp/p7/1p1P4/2p1P3/2PnRKN1/PP5q/8_b_-_-_5_37",
    "player": "Mihail Tal",
    "opponent": "A. Ostrauskas",
    "eco": "C86",
    "date": "1955",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Ba4",
      "Nf6",
      "Qe2",
      "b5",
      "Bb3",
      "Be7",
      "c3",
      "O-O",
      "O-O",
      "d6",
      "h3",
      "Na5",
      "Bc2",
      "c5",
      "d4",
      "Qc7",
      "d5",
      "Bd7",
      "Nh2",
      "c4",
      "g4",
      "Nb7",
      "f4",
      "exf4",
      "Bxf4",
      "Nc5",
      "Nd2",
      "Kh8",
      "Rae1",
      "Rae8",
      "Qg2",
      "Qb6",
      "Kh1",
      "Bc8",
      "Nhf3",
      "Nfd7",
      "Qg3",
      "f6",
      "g5",
      "fxg5",
      "Nxg5",
      "Bxg5",
      "Qxg5",
      "Ne5",
      "Bxe5",
      "dxe5",
      "Rxf8+",
      "Rxf8",
      "Qxe5",
      "Qh6",
      "Qh2",
      "Bxh3",
      "Nf3",
      "Qh5",
      "Ng1",
      "Bg2+",
      "Kxg2",
      "Rf2+",
      "Kxf2",
      "Qxh2+",
      "Kf3",
      "Qxc2",
      "Re3",
      "Qh2",
      "Ne2",
      "Nd3",
      "Ng3"
    ],
    "bestMove": "Ne5+",
    "mistakeMove": "Qxg3+",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_tal_bronstein-david-i_tal-mihail_73",
    "gameId": "famous-bronstein-david-i-tal-mihail-1972",
    "site": "https://lichess.org/analysis/n5k1/4r1pp/K5p1/2rp2P1/4p1BP/b3P3/5P2/R4R2_b_-_-_5_37",
    "player": "Mihail Tal",
    "opponent": "David I Bronstein",
    "eco": "A01",
    "date": "1972",
    "abdulsColor": "black",
    "setupMoves": [
      "b3",
      "d5",
      "Bb2",
      "Bg4",
      "h3",
      "Bh5",
      "Nf3",
      "Nd7",
      "e3",
      "e6",
      "Be2",
      "Ngf6",
      "d3",
      "Bd6",
      "Nbd2",
      "Qe7",
      "a3",
      "c6",
      "c4",
      "O-O",
      "g4",
      "Bg6",
      "Nh4",
      "Ne8",
      "Nxg6",
      "fxg6",
      "h4",
      "b5",
      "g5",
      "bxc4",
      "dxc4",
      "e5",
      "b4",
      "a5",
      "c5",
      "Bb8",
      "Qa4",
      "Qe6",
      "Rg1",
      "Nc7",
      "Bg4",
      "Qf7",
      "O-O-O",
      "axb4",
      "Qxc6",
      "bxa3",
      "Qxd7",
      "axb2+",
      "Kxb2",
      "Ba7",
      "Qxf7+",
      "Rxf7",
      "Rgf1",
      "Bxc5",
      "Nb3",
      "Ba3+",
      "Kc2",
      "Re7",
      "Kd3",
      "Rb8",
      "Na5",
      "e4+",
      "Kd4",
      "Rb4+",
      "Kc5",
      "Rb5+",
      "Kc6",
      "Rxa5",
      "Ra1",
      "Rc5+",
      "Kb6",
      "Na8+",
      "Ka6"
    ],
    "bestMove": "Rc6+",
    "mistakeMove": "Nc7+",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_tal_van-der-wiel-john-th_tal-mihail_83",
    "gameId": "famous-van-der-wiel-john-th-tal-mihail-1987",
    "site": "https://lichess.org/analysis/N1k5/5RB1/p1pr2p1/2p1p2p/P1n1P2P/5Pb1/4K3/8_b_-_-_3_42",
    "player": "Mihail Tal",
    "opponent": "John TH Van der Wiel",
    "eco": "C69",
    "date": "1987",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Bxc6",
      "dxc6",
      "O-O",
      "f6",
      "d4",
      "Bg4",
      "dxe5",
      "Qxd1",
      "Rxd1",
      "fxe5",
      "Rd3",
      "Bd6",
      "Nbd2",
      "b5",
      "b3",
      "Ne7",
      "Bb2",
      "Ng6",
      "g3",
      "O-O-O",
      "Kg2",
      "h6",
      "Rc1",
      "Kb7",
      "c4",
      "Bb4",
      "Rxd8",
      "Rxd8",
      "Nf1",
      "Bxf3+",
      "Kxf3",
      "Bc5",
      "Ke2",
      "Bd4",
      "Rd1",
      "c5",
      "Ne3",
      "Re8",
      "Bc1",
      "Ne7",
      "h4",
      "h5",
      "Ng2",
      "Nc6",
      "Bg5",
      "Na5",
      "Ne3",
      "g6",
      "Nd5",
      "Nc6",
      "Bf6",
      "Re6",
      "Bg7",
      "Kc8",
      "a4",
      "bxc4",
      "bxc4",
      "Na5",
      "Rc1",
      "Kd7",
      "f3",
      "Rd6",
      "Kd3",
      "c6",
      "Nb6+",
      "Kc7",
      "Rb1",
      "Bf2+",
      "Ke2",
      "Bxg3",
      "Na8+",
      "Kd7",
      "Rb6",
      "Nxc4",
      "Rb7+",
      "Kc8",
      "Rf7"
    ],
    "bestMove": "Rd2+",
    "mistakeMove": "Bxh4",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_capablanca_capablanca-jose-raul_vassaux-g_54",
    "gameId": "famous-capablanca-jose-raul-vassaux-g-1939",
    "site": "https://lichess.org/analysis/r3br1k/pp5p/4B1p1/4NpP1/P2Pn3/q1PQ3R/7P/3R2K1_w_-_-_1_28",
    "player": "Jose Raul Capablanca",
    "opponent": "G. Vassaux",
    "eco": "D47",
    "date": "1939",
    "abdulsColor": "white",
    "setupMoves": [
      "Nf3",
      "d5",
      "e3",
      "Nf6",
      "c4",
      "c6",
      "Nc3",
      "e6",
      "d4",
      "Nbd7",
      "Bd3",
      "dxc4",
      "Bxc4",
      "Bb4",
      "O-O",
      "O-O",
      "Qe2",
      "Qe7",
      "Ne5",
      "c5",
      "f4",
      "Nb6",
      "Bb3",
      "Nbd5",
      "Bd2",
      "Bxc3",
      "bxc3",
      "Ne4",
      "Be1",
      "f6",
      "Qd3",
      "f5",
      "a4",
      "Kh8",
      "g4",
      "Ndf6",
      "Bh4",
      "Bd7",
      "Rf3",
      "Be8",
      "Rh3",
      "Qd6",
      "gxf5",
      "exf5",
      "Rd1",
      "cxd4",
      "exd4",
      "Qa3",
      "Be6",
      "g6",
      "Bg5",
      "Nxg5",
      "fxg5",
      "Ne4"
    ],
    "bestMove": "Rxh7+",
    "mistakeMove": "Qxe4",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_capablanca_capablanca-jose-raul_lewis-j_67",
    "gameId": "famous-capablanca-jose-raul-lewis-j-1941",
    "site": "https://lichess.org/analysis/6k1/pp1R1p2/7p/3P3K/2P5/1P1q2P1/P5B1/5R2_b_-_-_0_34",
    "player": "J. Lewis",
    "opponent": "Jose Raul Capablanca",
    "eco": "B24",
    "date": "1941",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "c5",
      "Nc3",
      "Nc6",
      "g3",
      "d6",
      "Bg2",
      "e5",
      "d3",
      "Nf6",
      "Nge2",
      "Be7",
      "O-O",
      "O-O",
      "f4",
      "exf4",
      "Nxf4",
      "Ne5",
      "h3",
      "Bd7",
      "Ncd5",
      "Bc6",
      "c4",
      "h6",
      "b3",
      "Bxd5",
      "exd5",
      "Re8",
      "d4",
      "cxd4",
      "Qxd4",
      "Qc8",
      "Bb2",
      "Bd8",
      "Kh2",
      "Bb6",
      "Qc3",
      "Neg4+",
      "hxg4",
      "Re3",
      "Qxf6",
      "gxf6",
      "Nh5",
      "Bd8",
      "Rf4",
      "Re5",
      "Raf1",
      "Rg5",
      "Bxf6",
      "Rxh5+",
      "gxh5",
      "Bxf6",
      "Rxf6",
      "Qg4",
      "Bf3",
      "Qd4",
      "Rxd6",
      "Re8",
      "Rd7",
      "Qd2+",
      "Kh3",
      "Qd3",
      "Bg2",
      "Re5",
      "Kh4",
      "Rxh5+",
      "Kxh5"
    ],
    "bestMove": "Qg6+",
    "mistakeMove": "Qxf1",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_alekhine_alekhine-alexander_forrester_24",
    "gameId": "famous-alekhine-alexander-forrester-1923",
    "site": "https://lichess.org/analysis/r1b1k2r/2pp1ppp/pp2Pq2/b7/B2Q4/B1P5/P1P2PPP/R3K2R_w_KQkq_-_1_13",
    "player": "Alexander Alekhine",
    "opponent": "Forrester",
    "eco": "C77",
    "date": "1923",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Ba4",
      "Nf6",
      "Nc3",
      "Bc5",
      "Nxe5",
      "Nxe5",
      "d4",
      "Bb4",
      "dxe5",
      "Nxe4",
      "Qd4",
      "Nxc3",
      "bxc3",
      "Ba5",
      "Ba3",
      "b6",
      "e6",
      "Qf6"
    ],
    "bestMove": "Bxd7+",
    "mistakeMove": "Qxf6",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_alekhine_alekhine-alexander_vardonenko_50",
    "gameId": "famous-alekhine-alexander-vardonenko-1931",
    "site": "https://lichess.org/analysis/3r2kr/1pp4p/p4p2/7Q/2qN1B2/8/PPP3PP/4R2K_w_-_-_4_26",
    "player": "Alexander Alekhine",
    "opponent": "Vardonenko",
    "eco": "C30",
    "date": "1931",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "f6",
      "Nf3",
      "Nc6",
      "Nc3",
      "exf4",
      "d4",
      "d6",
      "Bxf4",
      "f5",
      "exf5",
      "Bxf5",
      "Bb5",
      "Bd7",
      "O-O",
      "a6",
      "Bc4",
      "Nf6",
      "Ng5",
      "d5",
      "Nxd5",
      "Bg4",
      "Re1+",
      "Be7",
      "Nxf6+",
      "gxf6",
      "Qxg4",
      "Qxd4+",
      "Kh1",
      "Qxc4",
      "Qh5+",
      "Kd7",
      "Qh3+",
      "Ke8",
      "Ne6",
      "Nd4",
      "Qh5+",
      "Kd7",
      "Nxd4",
      "Rad8",
      "Qg4+",
      "Ke8",
      "Rxe7+",
      "Kxe7",
      "Re1+",
      "Kf7",
      "Qh5+",
      "Kg8"
    ],
    "bestMove": "Re8+",
    "mistakeMove": "Qxh7+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_alekhine_alekhine-alexander_johner-paul-f_57",
    "gameId": "famous-alekhine-alexander-johner-paul-f-1911",
    "site": "https://lichess.org/analysis/2rr2k1/pp4pp/3N4/4P3/1Q1P4/4b3/PP3q1P/R2K4_b_-_-_3_29",
    "player": "Paul F Johner",
    "opponent": "Alexander Alekhine",
    "eco": "C31",
    "date": "1911",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "d5",
      "exd5",
      "c6",
      "Qe2",
      "cxd5",
      "fxe5",
      "Nc6",
      "c3",
      "d4",
      "Nf3",
      "Nge7",
      "d3",
      "Ng6",
      "Qe4",
      "Bc5",
      "Nbd2",
      "O-O",
      "Nb3",
      "f5",
      "Qe2",
      "Bb6",
      "Bg5",
      "Qd7",
      "Qd2",
      "f4",
      "cxd4",
      "Nxd4",
      "Nbxd4",
      "Bxd4",
      "Qb4",
      "Be3",
      "d4",
      "Qg4",
      "Bh4",
      "Nxh4",
      "Bc4+",
      "Be6",
      "Bxe6+",
      "Qxe6",
      "Nxh4",
      "Qg4",
      "Nf3",
      "Qxg2",
      "Rf1",
      "Rac8",
      "Nd2",
      "Rfd8",
      "Nc4",
      "f3",
      "Rxf3",
      "Qxf3",
      "Nd6",
      "Qf2+",
      "Kd1"
    ],
    "bestMove": "Qf1+",
    "mistakeMove": "Rxd6",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_alekhine_alekhine-alexander_verlinsky-boris_76",
    "gameId": "famous-alekhine-alexander-verlinsky-boris-1918",
    "site": "https://lichess.org/analysis/8/5R2/2pk1nr1/1pN1p2p/1PP1P2P/3P4/1K6/8_w_-_-_1_39",
    "player": "Alexander Alekhine",
    "opponent": "Boris Verlinsky",
    "eco": "C68",
    "date": "1918",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Bxc6",
      "dxc6",
      "Nc3",
      "Bc5",
      "d3",
      "Qe7",
      "Be3",
      "Bg4",
      "h3",
      "Bh5",
      "g4",
      "Bg6",
      "Qd2",
      "O-O-O",
      "Bxc5",
      "Qxc5",
      "Qe3",
      "Qxe3+",
      "fxe3",
      "f6",
      "O-O-O",
      "c5",
      "Nd5",
      "c6",
      "Nb6+",
      "Kc7",
      "Nc4",
      "b5",
      "Ncd2",
      "Ne7",
      "b3",
      "h5",
      "g5",
      "Rc8",
      "gxf6",
      "gxf6",
      "Rhg1",
      "Rhg8",
      "Kb2",
      "Kd7",
      "a4",
      "Ke6",
      "Ra1",
      "f5",
      "Ng5+",
      "Kd6",
      "axb5",
      "axb5",
      "exf5",
      "Bxf5",
      "Nde4+",
      "Bxe4",
      "Nxe4+",
      "Ke6",
      "Nxc5+",
      "Kd5",
      "Rxg8",
      "Nxg8",
      "b4",
      "Nf6",
      "e4+",
      "Kd6",
      "Ra7",
      "Rg8",
      "Rf7",
      "Rg6",
      "h4",
      "Rh6",
      "c4",
      "Rg6"
    ],
    "bestMove": "Nb7+",
    "mistakeMove": "Rxf6+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_alekhine_levenfish-grigory_alekhine-alexander_81",
    "gameId": "famous-levenfish-grigory-alekhine-alexander-1912",
    "site": "https://lichess.org/analysis/6k1/1p6/3p1p2/3Pp2p/PP3Pqn/8/1Q5K/4R3_b_-_-_0_41",
    "player": "Alexander Alekhine",
    "opponent": "Grigory Levenfish",
    "eco": "C77",
    "date": "1912",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Ba4",
      "Nf6",
      "Qe2",
      "Be7",
      "c3",
      "d6",
      "h3",
      "Bd7",
      "d3",
      "O-O",
      "Bc2",
      "Kh8",
      "O-O",
      "Ng8",
      "Re1",
      "Qe8",
      "d4",
      "f6",
      "Nbd2",
      "g5",
      "d5",
      "Nd8",
      "g4",
      "h5",
      "Nh2",
      "Nh6",
      "Ndf1",
      "c6",
      "Ng3",
      "cxd5",
      "exd5",
      "Qf7",
      "Nf5",
      "Nxf5",
      "Bxf5",
      "Bxf5",
      "gxf5",
      "Qh7",
      "Qe4",
      "Nf7",
      "Nf1",
      "Nh6",
      "Ne3",
      "Rg8",
      "Kg2",
      "Bd8",
      "a4",
      "a5",
      "b4",
      "axb4",
      "cxb4",
      "Bb6",
      "Nc4",
      "Bd4",
      "Bb2",
      "Rac8",
      "Rac1",
      "Rxc4",
      "Rxc4",
      "Bxb2",
      "Qc2",
      "Nxf5",
      "Rc7",
      "Qg6",
      "Rc8",
      "g4",
      "Rxg8+",
      "Kxg8",
      "Qxb2",
      "gxh3+",
      "Kxh3",
      "Qg4+",
      "Kh2",
      "Nh4",
      "f4"
    ],
    "bestMove": "Nf3+",
    "mistakeMove": "exf4",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_marshall_mason-james_marshall-frank-james_45",
    "gameId": "famous-mason-james-marshall-frank-james-1902",
    "site": "https://lichess.org/analysis/6k1/ppp3pp/8/3bp1K1/3r4/2N2r2/PPn2P1P/2R2BR1_b_-_-_13_23",
    "player": "Frank James Marshall",
    "opponent": "James Mason",
    "eco": "A21",
    "date": "1902",
    "abdulsColor": "black",
    "setupMoves": [
      "c4",
      "e5",
      "Nc3",
      "f5",
      "e4",
      "Nf6",
      "d3",
      "Nc6",
      "exf5",
      "Bb4",
      "Bd2",
      "O-O",
      "g4",
      "d5",
      "cxd5",
      "Bxc3",
      "Bxc3",
      "Qxd5",
      "Qf3",
      "Qc5",
      "Ne2",
      "Nb4",
      "Rc1",
      "Nxg4",
      "Qxg4",
      "Nxd3+",
      "Kd2",
      "Bxf5",
      "Bb4",
      "Qxb4+",
      "Qxb4",
      "Nxb4",
      "Nc3",
      "Rad8+",
      "Ke3",
      "Nc2+",
      "Kf3",
      "Rd4",
      "Rg1",
      "Be4+",
      "Kg3",
      "Rf3+",
      "Kg4",
      "Bd5+",
      "Kg5"
    ],
    "bestMove": "h6+",
    "mistakeMove": "Rxc3",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_marshall_marshall-frank-james_bogoljubow-efim_78",
    "gameId": "famous-marshall-frank-james-bogoljubow-efim-1924",
    "site": "https://lichess.org/analysis/3q4/4b3/2p4p/p2pQB2/N1k2P2/P5P1/1P5P/7K_w_-_-_7_40",
    "player": "Frank James Marshall",
    "opponent": "Efim Bogoljubow",
    "eco": "D52",
    "date": "1924",
    "abdulsColor": "white",
    "setupMoves": [
      "d4",
      "Nf6",
      "Nf3",
      "e6",
      "Bg5",
      "d5",
      "e3",
      "Nbd7",
      "c4",
      "c6",
      "cxd5",
      "exd5",
      "Nc3",
      "Qa5",
      "Bd3",
      "Ne4",
      "Qc2",
      "Nxg5",
      "Nxg5",
      "h6",
      "Nf3",
      "Be7",
      "O-O",
      "O-O",
      "a3",
      "Qd8",
      "Rae1",
      "a5",
      "Qe2",
      "Nf6",
      "Ne5",
      "Bd6",
      "f4",
      "c5",
      "Bb1",
      "Bd7",
      "Qc2",
      "Bc6",
      "dxc5",
      "Bxc5",
      "Kh1",
      "Re8",
      "e4",
      "Bd4",
      "Nxc6",
      "bxc6",
      "e5",
      "Ng4",
      "Qh7+",
      "Kf8",
      "g3",
      "Qb6",
      "Bf5",
      "Nf2+",
      "Rxf2",
      "Bxf2",
      "Qh8+",
      "Ke7",
      "Qxg7",
      "Kd8",
      "Qf6+",
      "Re7",
      "e6",
      "Bd4",
      "exf7",
      "Bxf6",
      "f8=Q+",
      "Kc7",
      "Rxe7+",
      "Bxe7",
      "Qxa8",
      "Kd6",
      "Qh8",
      "Qd8",
      "Qe5+",
      "Kc5",
      "Na4+",
      "Kc4"
    ],
    "bestMove": "Qc3+",
    "mistakeMove": "Qxe7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_pillsbury_showalter-jackson-whipps_pillsbury-harry-nelson_48",
    "gameId": "famous-showalter-jackson-whipps-pillsbury-harry-nelson-1897",
    "site": "https://lichess.org/analysis/1r4k1/pp1b3p/2n2Qp1/b6q/8/5N2/PPB2PPP/4R1K1_w_-_-_2_25",
    "player": "Jackson Whipps Showalter",
    "opponent": "Harry Nelson Pillsbury",
    "eco": "C67",
    "date": "1897",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "Nf6",
      "O-O",
      "Nxe4",
      "d4",
      "Nd6",
      "Ba4",
      "exd4",
      "c3",
      "dxc3",
      "Nxc3",
      "Be7",
      "Nd5",
      "O-O",
      "Re1",
      "Bf6",
      "Bf4",
      "Ne8",
      "Rxe8",
      "Qxe8",
      "Nxc7",
      "Qe4",
      "Bd6",
      "Rb8",
      "Bc2",
      "Qg4",
      "Bxf8",
      "Kxf8",
      "Qd6+",
      "Be7",
      "Re1",
      "g6",
      "Qd2",
      "Qh5",
      "Nd5",
      "Bd8",
      "Qc3",
      "f6",
      "Nxf6",
      "Ba5",
      "Nxd7+",
      "Bxd7",
      "Qf6+",
      "Kg8"
    ],
    "bestMove": "Bb3+",
    "mistakeMove": "Qxc6",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_pillsbury_pillsbury-harry-nelson_moreau-c_56",
    "gameId": "famous-pillsbury-harry-nelson-moreau-c-1903",
    "site": "https://lichess.org/analysis/4r1nQ/p4k2/2p1p3/q1p1P1p1/2P3P1/3R4/P1P2PKP/8_w_-_-_0_29",
    "player": "Harry Nelson Pillsbury",
    "opponent": "C. Moreau",
    "eco": "B45",
    "date": "1903",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "c5",
      "Nf3",
      "e6",
      "Nc3",
      "Nc6",
      "d4",
      "cxd4",
      "Nxd4",
      "Bb4",
      "Nxc6",
      "Bxc3+",
      "bxc3",
      "dxc6",
      "Bd3",
      "Nf6",
      "e5",
      "Nd5",
      "Qg4",
      "g6",
      "O-O",
      "Qc7",
      "Re1",
      "Bd7",
      "Qh4",
      "c5",
      "c4",
      "Ne7",
      "Bg5",
      "Ng8",
      "Be4",
      "Bc6",
      "Bxc6+",
      "bxc6",
      "Rad1",
      "h6",
      "Rd6",
      "Ne7",
      "g4",
      "Kf8",
      "Red1",
      "Ng8",
      "Bf6",
      "g5",
      "Bxg5",
      "hxg5",
      "Qxh8",
      "Re8",
      "Rd7",
      "Qb8",
      "Kg2",
      "Qb6",
      "R1d3",
      "Qa5",
      "Rxf7+",
      "Kxf7"
    ],
    "bestMove": "Qh7+",
    "mistakeMove": "Qxg8+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_pillsbury_pillsbury-harry-nelson_lasker-emanuel_59",
    "gameId": "famous-pillsbury-harry-nelson-lasker-emanuel-1895",
    "site": "https://lichess.org/analysis/8/p5pk/4Qb1p/1K1p4/3P4/2q5/P2R2PP/3R4_b_-_-_0_30",
    "player": "Emanuel Lasker",
    "opponent": "Harry Nelson Pillsbury",
    "eco": "D50",
    "date": "1895",
    "abdulsColor": "black",
    "setupMoves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "Nf3",
      "c5",
      "Bg5",
      "cxd4",
      "Qxd4",
      "Nc6",
      "Qh4",
      "Be7",
      "O-O-O",
      "Qa5",
      "e3",
      "Bd7",
      "Kb1",
      "h6",
      "cxd5",
      "exd5",
      "Nd4",
      "O-O",
      "Bxf6",
      "Bxf6",
      "Qh5",
      "Nxd4",
      "exd4",
      "Be6",
      "f4",
      "Rac8",
      "f5",
      "Rxc3",
      "fxe6",
      "Ra3",
      "exf7+",
      "Rxf7",
      "bxa3",
      "Qb6+",
      "Bb5",
      "Qxb5+",
      "Ka1",
      "Rc7",
      "Rd2",
      "Rc4",
      "Rhd1",
      "Rc3",
      "Qf5",
      "Qc4",
      "Kb2",
      "Rxa3",
      "Qe6+",
      "Kh7",
      "Kxa3",
      "Qc3+",
      "Ka4",
      "b5+",
      "Kxb5"
    ],
    "bestMove": "Qc4+",
    "mistakeMove": "Qxd2",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_spielmann_schenkein-j_spielmann-rudolf_41",
    "gameId": "famous-schenkein-j-spielmann-rudolf-1910",
    "site": "https://lichess.org/analysis/2k5/ppp5/6p1/4Qb2/1P1K2p1/P7/2q4P/RNB4R_b_-_-_1_21",
    "player": "Rudolf Spielmann",
    "opponent": "J. Schenkein",
    "eco": "A02",
    "date": "1910",
    "abdulsColor": "black",
    "setupMoves": [
      "f4",
      "e5",
      "fxe5",
      "d6",
      "exd6",
      "Bxd6",
      "Nf3",
      "g5",
      "g3",
      "g4",
      "Nh4",
      "Ne7",
      "d4",
      "Ng6",
      "Ng2",
      "Nc6",
      "e3",
      "h5",
      "Bd3",
      "h4",
      "Bxg6",
      "fxg6",
      "Nxh4",
      "Rxh4",
      "gxh4",
      "Qxh4+",
      "Kd2",
      "Bf5",
      "a3",
      "O-O-O",
      "Kc3",
      "Be5",
      "b4",
      "Nxd4",
      "exd4",
      "Rxd4",
      "Qxd4",
      "Qf2",
      "Qxe5",
      "Qxc2+",
      "Kd4"
    ],
    "bestMove": "Qd3+",
    "mistakeMove": "Qxc1",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_blackburne_steinkuehler-g_blackburne-joseph-henry_39",
    "gameId": "famous-steinkuehler-g-blackburne-joseph-henry-1863",
    "site": "https://lichess.org/analysis/r1b2r1k/pp4pp/3p4/3B4/8/1QN3Pn/PP3q1P/R3R2K_b_-_-_1_20",
    "player": "Joseph Henry Blackburne",
    "opponent": "G. Steinkuehler",
    "eco": "C54",
    "date": "1863",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "c3",
      "Nf6",
      "d4",
      "exd4",
      "cxd4",
      "Bb4+",
      "Bd2",
      "Bxd2+",
      "Nfxd2",
      "Nxd4",
      "O-O",
      "d6",
      "Nb3",
      "Nxb3",
      "Qxb3",
      "O-O",
      "Re1",
      "Nh5",
      "e5",
      "Qg5",
      "exd6",
      "Nf4",
      "Bxf7+",
      "Kh8",
      "g3",
      "cxd6",
      "Nc3",
      "Nh3+",
      "Kg2",
      "Qf6",
      "Bd5",
      "Qxf2+",
      "Kh1"
    ],
    "bestMove": "Qg1+",
    "mistakeMove": "Qxe1+",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_blackburne_blackburne-joseph-henry_nn_40",
    "gameId": "famous-blackburne-joseph-henry-nn-1875",
    "site": "https://lichess.org/analysis/rn4k1/pppb1p1p/7B/3PR2N/3P2pP/3B4/P1P1K1P1/7q_w_-_-_0_21",
    "player": "Joseph Henry Blackburne",
    "opponent": "NN",
    "eco": "C39",
    "date": "1875",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "h4",
      "g4",
      "Ne5",
      "Bg7",
      "d4",
      "Nf6",
      "Bc4",
      "d5",
      "exd5",
      "O-O",
      "Nc3",
      "Nh5",
      "Ne2",
      "Re8",
      "Nxf4",
      "Bxe5",
      "Nxh5",
      "Bg3+",
      "Kf1",
      "Re1+",
      "Qxe1",
      "Bxe1",
      "Bg5",
      "Qd6",
      "Rxe1",
      "Bd7",
      "Re5",
      "Qb4",
      "Bd3",
      "Qxb2",
      "Bh6",
      "Qa1+",
      "Ke2",
      "Qxh1"
    ],
    "bestMove": "Rg5+",
    "mistakeMove": "Bxh7+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_blackburne_blackburne-joseph-henry_peyer-t_42",
    "gameId": "famous-blackburne-joseph-henry-peyer-t-1875",
    "site": "https://lichess.org/analysis/rkq4r/ppR2ppp/B7/1b1pP3/8/B7/P4PPP/2R3K1_w_-_-_0_22",
    "player": "Joseph Henry Blackburne",
    "opponent": "T. Peyer",
    "eco": "C52",
    "date": "1875",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "b4",
      "Bxb4",
      "c3",
      "Ba5",
      "O-O",
      "Nf6",
      "d4",
      "exd4",
      "Ba3",
      "d6",
      "e5",
      "Ne4",
      "Re1",
      "d5",
      "Bb5",
      "Nxc3",
      "Nxc3",
      "Bxc3",
      "Nxd4",
      "Bxd4",
      "Qxd4",
      "Be6",
      "Rac1",
      "Qd7",
      "Qa4",
      "Kd8",
      "Rxc6",
      "Kc8",
      "Rec1",
      "Kb8",
      "Ba6",
      "Qc8",
      "Qb5",
      "Bd7",
      "Rxc7",
      "Bxb5"
    ],
    "bestMove": "Rxb7+",
    "mistakeMove": "Rxc8+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_blackburne_blackburne-joseph-henry_steinitz-william_48",
    "gameId": "famous-blackburne-joseph-henry-steinitz-william-1883",
    "site": "https://lichess.org/analysis/r1n5/pp2q1kp/2ppr1p1/4p1Q1/8/2N4R/PPP3PP/5RK1_w_-_-_2_25",
    "player": "Joseph Henry Blackburne",
    "opponent": "William Steinitz",
    "eco": "C46",
    "date": "1883",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Nc3",
      "g6",
      "d4",
      "exd4",
      "Nxd4",
      "Bg7",
      "Be3",
      "Nf6",
      "Be2",
      "O-O",
      "O-O",
      "Ne7",
      "Bf3",
      "d6",
      "Qd2",
      "Nd7",
      "Bh6",
      "Ne5",
      "Bxg7",
      "Kxg7",
      "Be2",
      "f6",
      "f4",
      "Nf7",
      "Rad1",
      "c6",
      "Bc4",
      "Bd7",
      "Bxf7",
      "Rxf7",
      "f5",
      "Nc8",
      "e5",
      "fxe5",
      "Ne6+",
      "Bxe6",
      "fxe6",
      "Re7",
      "Qg5",
      "Qe8",
      "Rd3",
      "Rxe6",
      "Rh3",
      "Qe7"
    ],
    "bestMove": "Qh6+",
    "mistakeMove": "Qxe7+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_blackburne_blackburne-joseph-henry_nn_50",
    "gameId": "famous-blackburne-joseph-henry-nn-1875",
    "site": "https://lichess.org/analysis/3rk2r/1p3pp1/1Q6/p5qp/P7/B1P5/5PPP/3R2K1_w_k_-_0_26",
    "player": "Joseph Henry Blackburne",
    "opponent": "NN",
    "eco": "C52",
    "date": "1875",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "b4",
      "Bxb4",
      "c3",
      "Ba5",
      "O-O",
      "d6",
      "d4",
      "Bb6",
      "a4",
      "a5",
      "dxe5",
      "Bg4",
      "Qb3",
      "Qe7",
      "exd6",
      "Qd7",
      "e5",
      "Be6",
      "Na3",
      "Nd8",
      "Rd1",
      "Bxc4",
      "Nxc4",
      "Bc5",
      "dxc7",
      "Qxc7",
      "Nd6+",
      "Bxd6",
      "exd6",
      "Qd7",
      "Ne5",
      "Qe6",
      "Ba3",
      "Nf6",
      "d7+",
      "Nxd7",
      "Rxd7",
      "Qxe5",
      "Rad1",
      "h5",
      "Qb6",
      "Qg5",
      "Rxd8+",
      "Rxd8"
    ],
    "bestMove": "Re1+",
    "mistakeMove": "Qxd8+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_blackburne_pitschel-karl_blackburne-joseph-henry_53",
    "gameId": "famous-pitschel-karl-blackburne-joseph-henry-1873",
    "site": "https://lichess.org/analysis/3r3k/1ppq2pp/r4pn1/p3p2K/3pP2P/P2P1N2/BPPB1P2/2RQ3R_b_-_-_0_27",
    "player": "Joseph Henry Blackburne",
    "opponent": "Karl Pitschel",
    "eco": "C50",
    "date": "1873",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "Nc3",
      "d6",
      "h3",
      "Nc6",
      "Nf3",
      "Ne7",
      "Be3",
      "Bb4",
      "O-O",
      "Ng6",
      "Ne2",
      "O-O",
      "Ng3",
      "d5",
      "Bb3",
      "d4",
      "Bd2",
      "Bd6",
      "Re1",
      "Nd7",
      "a3",
      "Nc5",
      "Ba2",
      "Ne6",
      "Nf5",
      "Be7",
      "Nxe7+",
      "Qxe7",
      "Rc1",
      "Nef4",
      "Kh2",
      "Kh8",
      "g4",
      "Rd8",
      "Rg1",
      "a5",
      "Kg3",
      "Ra6",
      "h4",
      "Bxg4",
      "Rh1",
      "Nh5+",
      "Kxg4",
      "Qd7+",
      "Kg5",
      "f6+",
      "Kxh5"
    ],
    "bestMove": "Nf4+",
    "mistakeMove": "Nxh4",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_chigorin_chigorin-mikhail_schiffers-emanuel-stepanovich_50",
    "gameId": "famous-chigorin-mikhail-schiffers-emanuel-stepanovich-1880",
    "site": "https://lichess.org/analysis/7q/p1p1Rrkp/2p3p1/2N3P1/5P2/2pB4/PP5P/6K1_w_-_-_1_26",
    "player": "Mikhail Chigorin",
    "opponent": "Emanuel Stepanovich Schiffers",
    "eco": "C45",
    "date": "1880",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Nxd4",
      "Bc5",
      "Be3",
      "Qf6",
      "c3",
      "Nge7",
      "Bc4",
      "d6",
      "f4",
      "Qg6",
      "O-O",
      "Qxe4",
      "Re1",
      "Qg6",
      "Nxc6",
      "Bxe3+",
      "Rxe3",
      "bxc6",
      "Qe2",
      "Qf6",
      "Nd2",
      "d5",
      "Bd3",
      "Be6",
      "Rf1",
      "g6",
      "Nb3",
      "O-O",
      "g4",
      "Rae8",
      "Nc5",
      "d4",
      "g5",
      "Qh8",
      "Rxe6",
      "fxe6",
      "Qxe6+",
      "Kg7",
      "Re1",
      "dxc3",
      "Qxe7+",
      "Rxe7",
      "Rxe7+",
      "Rf7"
    ],
    "bestMove": "Ne6+",
    "mistakeMove": "Rxf7+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_chigorin_schiffers-emanuel-stepanovich_chigorin-mikhail_61",
    "gameId": "famous-schiffers-emanuel-stepanovich-chigorin-mikhail-1879",
    "site": "https://lichess.org/analysis/5rn1/1Q4bk/2pp3p/2p1p3/2Pq4/1P6/P4P1N/2K3RR_b_-_-_1_31",
    "player": "Mikhail Chigorin",
    "opponent": "Emanuel Stepanovich Schiffers",
    "eco": "C77",
    "date": "1879",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Ba4",
      "Nf6",
      "d3",
      "d6",
      "Bxc6+",
      "bxc6",
      "h3",
      "g6",
      "Nc3",
      "Bg7",
      "Bg5",
      "h6",
      "Be3",
      "O-O",
      "Qd2",
      "Kh7",
      "g4",
      "Ng8",
      "O-O-O",
      "c5",
      "Rdg1",
      "c6",
      "h4",
      "f6",
      "Ne2",
      "Qe7",
      "Qc3",
      "Rb8",
      "Nh2",
      "f5",
      "gxf5",
      "gxf5",
      "exf5",
      "Bxf5",
      "Ng3",
      "Rb4",
      "Ne4",
      "Bxe4",
      "dxe4",
      "Qe6",
      "b3",
      "Rxe4",
      "Qd3",
      "Qd5",
      "Qxa6",
      "Rxh4",
      "c4",
      "Qd3",
      "Qb7",
      "Qc3+",
      "Kd1",
      "Rd4+",
      "Bxd4",
      "Qxd4+",
      "Kc1"
    ],
    "bestMove": "Qa1+",
    "mistakeMove": "Rxf2",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_chigorin_chigorin-mikhail_bird-henry-edward_84",
    "gameId": "famous-chigorin-mikhail-bird-henry-edward-1889",
    "site": "https://lichess.org/analysis/2r1r3/p7/3B1n1p/7q/8/4kP2/PR4PP/1Q4K1_w_-_-_9_43",
    "player": "Mikhail Chigorin",
    "opponent": "Henry Edward Bird",
    "eco": "C44",
    "date": "1889",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "c3",
      "d5",
      "Qa4",
      "dxe4",
      "Nxe5",
      "Qd5",
      "Nxc6",
      "bxc6",
      "Bc4",
      "Qd6",
      "d3",
      "exd3",
      "O-O",
      "Be7",
      "Bxd3",
      "Bd7",
      "Rd1",
      "Nf6",
      "Na3",
      "Ng4",
      "Bf4",
      "Qc5",
      "Bg3",
      "Bd6",
      "Qe4+",
      "Kf8",
      "Qf3",
      "Be6",
      "b4",
      "Qxc3",
      "Nb5",
      "Qxb4",
      "Nxd6",
      "cxd6",
      "Bf5",
      "Kg8",
      "Bxe6",
      "fxe6",
      "Qxc6",
      "Kf7",
      "Rab1",
      "Qc5",
      "Qd7+",
      "Kg6",
      "Rb7",
      "Rag8",
      "Qf7+",
      "Kh6",
      "Qxe6+",
      "Nf6",
      "Bf4+",
      "Kg6",
      "Rb3",
      "h6",
      "Rg3+",
      "Kh7",
      "Bxd6",
      "Qh5",
      "Rc1",
      "Rc8",
      "Rb1",
      "Rhe8",
      "Rxg7+",
      "Kxg7",
      "Rb7+",
      "Kg6",
      "Qf7+",
      "Kf5",
      "Rb5+",
      "Ke4",
      "f3+",
      "Ke3",
      "Qb3+",
      "Ke2",
      "Qb2+",
      "Kd3",
      "Qb1+",
      "Ke2",
      "Rb2+",
      "Ke3"
    ],
    "bestMove": "Qe1+",
    "mistakeMove": "Bc7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_zukertort_rosenthal-samuel_zukertort-johannes-hermann_57",
    "gameId": "famous-rosenthal-samuel-zukertort-johannes-hermann-1878",
    "site": "https://lichess.org/analysis/2k5/2pq2p1/P2pB1p1/4p2r/4P3/1Q1Pn1K1/PP3r2/R7_b_-_-_0_29",
    "player": "Johannes Hermann Zukertort",
    "opponent": "Samuel Rosenthal",
    "eco": "C77",
    "date": "1878",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Ba4",
      "Nf6",
      "Nc3",
      "Bc5",
      "O-O",
      "b5",
      "Bb3",
      "d6",
      "d3",
      "Bg4",
      "h3",
      "Bh5",
      "g4",
      "Bg6",
      "Nd5",
      "Qd7",
      "Be3",
      "Bxe3",
      "fxe3",
      "h5",
      "Nh4",
      "Nxd5",
      "Bxd5",
      "O-O-O",
      "Nxg6",
      "fxg6",
      "c4",
      "Ne7",
      "Bf7",
      "hxg4",
      "cxb5",
      "Rxh3",
      "bxa6",
      "g3",
      "Rf5",
      "Nxf5",
      "Qb3",
      "Rdh8",
      "Be6",
      "Rh1+",
      "Kg2",
      "R8h2+",
      "Kf3",
      "Rf2+",
      "Kg4",
      "Rh4+",
      "Kg5",
      "Rh5+",
      "Kg4",
      "Nxe3+",
      "Kxg3"
    ],
    "bestMove": "Rg2+",
    "mistakeMove": "Qxe6",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_zukertort_steinitz-william_zukertort-johannes-hermann_84",
    "gameId": "famous-steinitz-william-zukertort-johannes-hermann-1872",
    "site": "https://lichess.org/analysis/4Q2R/pq4r1/5k2/1p6/3P4/1P3pP1/P7/5K2_w_-_-_9_43",
    "player": "William Steinitz",
    "opponent": "Johannes Hermann Zukertort",
    "eco": "C37",
    "date": "1872",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "Bc4",
      "g4",
      "Ne5",
      "Qh4+",
      "Kf1",
      "Nh6",
      "d4",
      "f3",
      "Nc3",
      "d6",
      "Nd3",
      "Bg7",
      "g3",
      "Qd8",
      "Nf4",
      "O-O",
      "h3",
      "Nc6",
      "Nh5",
      "gxh3",
      "Nd5",
      "Ng4",
      "c3",
      "Ne7",
      "Ndf4",
      "Ng6",
      "Nxh3",
      "Be6",
      "Bxe6",
      "fxe6",
      "Ng5",
      "Bh6",
      "Qb3",
      "Bxg5",
      "Qxe6+",
      "Rf7",
      "Qxg4",
      "Bxc1",
      "Rxc1",
      "Qe8",
      "c4",
      "d5",
      "e5",
      "dxc4",
      "Rxc4",
      "Qb5",
      "b3",
      "Qa6",
      "Nf6+",
      "Rxf6",
      "exf6",
      "Qxf6",
      "Rxc7",
      "Re8",
      "Qd7",
      "Qa6+",
      "Rc4",
      "Re7",
      "Qd5+",
      "Kg7",
      "Rh2",
      "b5",
      "Rc6",
      "Qb7",
      "Rxh7+",
      "Kxh7",
      "Qh5+",
      "Kg8",
      "Rxg6+",
      "Rg7",
      "Rh6",
      "Kf8",
      "Rh8+",
      "Ke7",
      "Qe5+",
      "Kf7",
      "Qe8+",
      "Kf6"
    ],
    "bestMove": "Rh6+",
    "mistakeMove": "Qxb5",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_bird_bird-henry-edward_nn_22",
    "gameId": "famous-bird-henry-edward-nn-1869",
    "site": "https://lichess.org/analysis/r1b1k2r/ppppbN1p/2n2n2/7Q/3PP3/2N5/PPP4P/R1B1KB1q_w_Qkq_-_1_12",
    "player": "Henry Edward Bird",
    "opponent": "NN",
    "eco": "C37",
    "date": "1869",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Nf3",
      "g5",
      "d4",
      "g4",
      "Ne5",
      "Qh4+",
      "g3",
      "fxg3",
      "Qxg4",
      "g2+",
      "Qxh4",
      "gxh1=Q",
      "Nc3",
      "Be7",
      "Qh5",
      "Nc6",
      "Nxf7",
      "Nf6"
    ],
    "bestMove": "Nd6+",
    "mistakeMove": "Nxh8+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_bird_steinitz-william_bird-henry-edward_53",
    "gameId": "famous-steinitz-william-bird-henry-edward-1866",
    "site": "https://lichess.org/analysis/3r1rk1/p1p4p/8/1PP1p1bq/2P5/3N1Pp1/PB2Q3/1R3RK1_b_-_-_2_27",
    "player": "Henry Edward Bird",
    "opponent": "William Steinitz",
    "eco": "C10",
    "date": "1866",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "dxe4",
      "Nxe4",
      "f5",
      "Ng5",
      "Be7",
      "N1h3",
      "Nc6",
      "Bb5",
      "Nf6",
      "O-O",
      "O-O",
      "Bxc6",
      "bxc6",
      "Nf4",
      "Qd6",
      "c4",
      "c5",
      "dxc5",
      "Qc6",
      "b4",
      "Ng4",
      "Nf3",
      "Bf6",
      "Rb1",
      "g5",
      "Nd3",
      "e5",
      "Nxg5",
      "f4",
      "b5",
      "Qe8",
      "Ne4",
      "Bf5",
      "f3",
      "Nxh2",
      "Kxh2",
      "Qh5+",
      "Kg1",
      "Rad8",
      "Qe2",
      "Bh4",
      "g4",
      "fxg3",
      "Bb2",
      "Bxe4",
      "Qxe4",
      "Bg5",
      "Qe2"
    ],
    "bestMove": "Be3+",
    "mistakeMove": "Rxd3",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_steinitz_steinitz-william_rock_30",
    "gameId": "famous-steinitz-william-rock-1863",
    "site": "https://lichess.org/analysis/r2q3r/ppp2Ppp/1b2Bn2/1k2N3/3p4/BnP5/P4PPP/RN2R1K1_w_-_-_5_16",
    "player": "William Steinitz",
    "opponent": "Rock",
    "eco": "C52",
    "date": "1863",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "b4",
      "Bxb4",
      "c3",
      "Ba5",
      "d4",
      "exd4",
      "O-O",
      "Nf6",
      "Ba3",
      "Bb6",
      "Qb3",
      "d5",
      "exd5",
      "Na5",
      "Re1+",
      "Be6",
      "dxe6",
      "Nxb3",
      "exf7+",
      "Kd7",
      "Be6+",
      "Kc6",
      "Ne5+",
      "Kb5"
    ],
    "bestMove": "Bc4+",
    "mistakeMove": "Bxb3",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_steinitz_steinitz-william_gray_30",
    "gameId": "famous-steinitz-william-gray-1872",
    "site": "https://lichess.org/analysis/3r2nr/pkp1q1pp/2npbp2/3B4/4P3/B1Q2N2/P4PPP/4R1K1_w_-_-_0_16",
    "player": "William Steinitz",
    "opponent": "Gray",
    "eco": "C52",
    "date": "1872",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "b4",
      "Bxb4",
      "c3",
      "Ba5",
      "d4",
      "exd4",
      "O-O",
      "dxc3",
      "Qb3",
      "Qe7",
      "Nxc3",
      "Bxc3",
      "Qxc3",
      "f6",
      "Ba3",
      "d6",
      "Bd5",
      "Bd7",
      "Rfe1",
      "O-O-O",
      "Rab1",
      "Be6",
      "Rxb7",
      "Kxb7"
    ],
    "bestMove": "Qxc6+",
    "mistakeMove": "Bxc6+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_steinitz_steinitz-william_lange-max_40",
    "gameId": "famous-steinitz-william-lange-max-1860",
    "site": "https://lichess.org/analysis/4rb1r/pp5p/1q2bP1p/2pPP3/2k5/2N5/PP4PP/R4R1K_w_-_-_0_21",
    "player": "William Steinitz",
    "opponent": "Max Lange",
    "eco": "C44",
    "date": "1860",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "d4",
      "exd4",
      "Bc4",
      "Qe7",
      "O-O",
      "Ne5",
      "Nxe5",
      "Qxe5",
      "c3",
      "c5",
      "f4",
      "Qf6",
      "e5",
      "Qb6",
      "Kh1",
      "Be7",
      "f5",
      "d5",
      "Bxd5",
      "Nh6",
      "f6",
      "Bf8",
      "Bxh6",
      "gxh6",
      "Bxf7+",
      "Kxf7",
      "Qh5+",
      "Ke6",
      "Qe8+",
      "Kd5",
      "cxd4",
      "Be6",
      "Nc3+",
      "Kc4",
      "d5",
      "Rxe8"
    ],
    "bestMove": "Rf4+",
    "mistakeMove": "dxe6",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_steinitz_robey-j_steinitz-william_40",
    "gameId": "famous-robey-j-steinitz-william-1865",
    "site": "https://lichess.org/analysis/r1b4r/pp3B1p/1b3Qpk/n1p2n2/8/3N4/PB3PPP/5RK1_w_-_-_6_21",
    "player": "J. Robey",
    "opponent": "William Steinitz",
    "eco": "C51",
    "date": "1865",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Bc5",
      "b4",
      "Bxb4",
      "c3",
      "Bc5",
      "O-O",
      "d6",
      "d4",
      "exd4",
      "cxd4",
      "Bb6",
      "Nc3",
      "Na5",
      "e5",
      "dxe5",
      "Bxf7+",
      "Kf8",
      "Ba3+",
      "Ne7",
      "Nxe5",
      "Qxd4",
      "Qh5",
      "Qxc3",
      "Rad1",
      "c5",
      "Rd3",
      "Qxd3",
      "Nxd3",
      "g6",
      "Qf3",
      "Kg7",
      "Bb2+",
      "Kh6",
      "Qf6",
      "Nf5"
    ],
    "bestMove": "Bc1+",
    "mistakeMove": "Qxh8",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_steinitz_hamppe-carl_steinitz-william_41",
    "gameId": "famous-hamppe-carl-steinitz-william-1859",
    "site": "https://lichess.org/analysis/1k1r4/ppp2ppp/8/1Q2P3/8/b1q4B/PRP4P/2K4R_b_-_-_8_21",
    "player": "William Steinitz",
    "opponent": "Carl Hamppe",
    "eco": "C29",
    "date": "1859",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nc3",
      "Nf6",
      "f4",
      "d5",
      "exd5",
      "Nxd5",
      "fxe5",
      "Nxc3",
      "bxc3",
      "Qh4+",
      "Ke2",
      "Bg4+",
      "Nf3",
      "Nc6",
      "d4",
      "O-O-O",
      "Bd2",
      "Bxf3+",
      "gxf3",
      "Nxe5",
      "dxe5",
      "Bc5",
      "Qe1",
      "Qc4+",
      "Kd1",
      "Qxc3",
      "Rb1",
      "Qxf3+",
      "Qe2",
      "Rxd2+",
      "Kxd2",
      "Rd8+",
      "Kc1",
      "Ba3+",
      "Rb2",
      "Qc3",
      "Bh3+",
      "Kb8",
      "Qb5"
    ],
    "bestMove": "Qd2+",
    "mistakeMove": "Bxb2+",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_steinitz_nn_steinitz-william_43",
    "gameId": "famous-nn-steinitz-william-1865",
    "site": "https://lichess.org/analysis/N2k2r1/pp1n1p2/3Q3p/8/3Nq3/7b/PPPP1K2/R1B4R_b_-_-_1_22",
    "player": "William Steinitz",
    "opponent": "NN",
    "eco": "C33",
    "date": "1865",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "exf4",
      "Bc4",
      "d5",
      "Bxd5",
      "Qh4+",
      "Kf1",
      "Ne7",
      "Nc3",
      "g5",
      "Nf3",
      "Qh5",
      "h4",
      "h6",
      "Kg1",
      "g4",
      "Nd4",
      "f3",
      "gxf3",
      "gxf3",
      "Qxf3",
      "Rg8+",
      "Kf1",
      "Bg4",
      "Qf6",
      "Nd7",
      "Qf4",
      "Nxd5",
      "Nxd5",
      "Bc5",
      "Nxc7+",
      "Kd8",
      "Nxa8",
      "Bh3+",
      "Ke1",
      "Bd6",
      "Qxd6",
      "Qxh4+",
      "Ke2",
      "Qxe4+",
      "Kf2"
    ],
    "bestMove": "Rg2+",
    "mistakeMove": "Qxh1",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_reti_euwe-max_reti-richard_39",
    "gameId": "famous-euwe-max-reti-richard-1920",
    "site": "https://lichess.org/analysis/Q7/ppp2kpp/8/2b5/4RP1q/8/PPP3KP/3R4_b_-_-_0_20",
    "player": "Richard Reti",
    "opponent": "Max Euwe",
    "eco": "C56",
    "date": "1920",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d4",
      "exd4",
      "O-O",
      "Nxe4",
      "Re1",
      "d5",
      "Bxd5",
      "Qxd5",
      "Nc3",
      "Qa5",
      "Nxd4",
      "Nxd4",
      "Qxd4",
      "f5",
      "Bg5",
      "Qc5",
      "Qd8+",
      "Kf7",
      "Nxe4",
      "fxe4",
      "Rad1",
      "Bd6",
      "Qxh8",
      "Qxg5",
      "f4",
      "Qh4",
      "Rxe4",
      "Bh3",
      "Qxa8",
      "Bc5+",
      "Kh1",
      "Bxg2+",
      "Kxg2"
    ],
    "bestMove": "Qg4+",
    "mistakeMove": "Qxh2+",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_reti_euwe-max_reti-richard_56",
    "gameId": "famous-euwe-max-reti-richard-1920",
    "site": "https://lichess.org/analysis/3R4/k3nqp1/pp6/8/N7/BP6/P1P4p/7K_w_-_-_0_29",
    "player": "Max Euwe",
    "opponent": "Richard Reti",
    "eco": "B10",
    "date": "1920",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "c6",
      "b3",
      "d5",
      "exd5",
      "cxd5",
      "Bb2",
      "Nc6",
      "g3",
      "e5",
      "Bg2",
      "Be6",
      "Qe2",
      "Qc7",
      "Nf3",
      "f6",
      "O-O",
      "Bd6",
      "Nc3",
      "a6",
      "d4",
      "Nge7",
      "dxe5",
      "Bxe5",
      "Nxe5",
      "fxe5",
      "Rad1",
      "O-O-O",
      "Rfe1",
      "h5",
      "Na4",
      "e4",
      "f3",
      "h4",
      "fxe4",
      "hxg3",
      "exd5",
      "Bxd5",
      "Bxd5",
      "Nxd5",
      "Qe6+",
      "Kb8",
      "Rxd5",
      "Rde8",
      "Qxe8+",
      "Rxe8",
      "Rxe8+",
      "Ka7",
      "Rdd8",
      "b6",
      "Ba3",
      "gxh2+",
      "Kh1",
      "Qf7",
      "Re7+",
      "Nxe7"
    ],
    "bestMove": "Rd7+",
    "mistakeMove": "Bxe7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_reti_reti-richard_de-leeuw-remco_62",
    "gameId": "famous-reti-richard-de-leeuw-remco-1919",
    "site": "https://lichess.org/analysis/r5r1/1q2bbpk/7p/2p1BP1P/pp2P3/6Q1/1PP3P1/2KR3R_w_-_-_1_32",
    "player": "Richard Reti",
    "opponent": "Remco De Leeuw",
    "eco": "C77",
    "date": "1919",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Ba4",
      "Nf6",
      "Nc3",
      "d6",
      "d4",
      "Bd7",
      "Bxc6",
      "Bxc6",
      "Bg5",
      "Be7",
      "Qd3",
      "exd4",
      "Nxd4",
      "Bd7",
      "O-O-O",
      "O-O",
      "h4",
      "Ng4",
      "Qd2",
      "f6",
      "Bf4",
      "c6",
      "Bg3",
      "b5",
      "f4",
      "b4",
      "Nb1",
      "a5",
      "f5",
      "Ne5",
      "h5",
      "h6",
      "Bf4",
      "Kh7",
      "Nf3",
      "Be8",
      "Qe2",
      "Qc7",
      "Nh4",
      "Bf7",
      "Ng6",
      "Rg8",
      "Nd2",
      "a4",
      "Nf3",
      "Bxa2",
      "Qf2",
      "c5",
      "Qg3",
      "Bf7",
      "Ngxe5",
      "dxe5",
      "Nxe5",
      "fxe5",
      "Bxe5",
      "Qb7"
    ],
    "bestMove": "Qg6+",
    "mistakeMove": "Bxg7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_nimzowitsch_nimzowitsch-aaron_romi-massimiliano_58",
    "gameId": "famous-nimzowitsch-aaron-romi-massimiliano-1930",
    "site": "https://lichess.org/analysis/1r2kr2/p2b3R/1pBp4/nPpN4/Q1PbPp2/P2P4/3KNq2/7R_w_-_-_1_30",
    "player": "Aaron Nimzowitsch",
    "opponent": "Massimiliano Romi",
    "eco": "A21",
    "date": "1930",
    "abdulsColor": "white",
    "setupMoves": [
      "c4",
      "e5",
      "Nc3",
      "c5",
      "g3",
      "d6",
      "Bg2",
      "Nc6",
      "d3",
      "f5",
      "a3",
      "Bd7",
      "b4",
      "Rb8",
      "b5",
      "Na5",
      "Bd5",
      "Nf6",
      "Bg5",
      "Be7",
      "Bxf6",
      "Bxf6",
      "Rc1",
      "Qe7",
      "e4",
      "g6",
      "Rb1",
      "Rf8",
      "h4",
      "f4",
      "Nge2",
      "Bg7",
      "h5",
      "gxh5",
      "gxf4",
      "exf4",
      "f3",
      "h4",
      "Kd2",
      "h3",
      "Qa4",
      "b6",
      "Bc6",
      "Qh4",
      "Rh2",
      "Qh5",
      "Rg1",
      "Bh8",
      "Rgh1",
      "Qxf3",
      "Nd5",
      "Bd4",
      "Rxh3",
      "Qf2",
      "R3h2",
      "Qf3",
      "Rxh7",
      "Qf2"
    ],
    "bestMove": "Re7+",
    "mistakeMove": "Rxd7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_bronstein_henriksen-morten_bronstein-david-i_59",
    "gameId": "famous-henriksen-morten-bronstein-david-i-1994",
    "site": "https://lichess.org/analysis/rn4k1/1p5p/p2p2p1/2pPb3/2P1PrPq/PN6/1P1QB2P/R2N2RK_b_-_-_0_30",
    "player": "David I Bronstein",
    "opponent": "Morten Henriksen",
    "eco": "E92",
    "date": "1994",
    "abdulsColor": "black",
    "setupMoves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
      "e5",
      "Be3",
      "Ng4",
      "Bg5",
      "Qe8",
      "d5",
      "f5",
      "Nd2",
      "Nf6",
      "f3",
      "c5",
      "O-O",
      "Nh5",
      "a3",
      "Bf6",
      "Be3",
      "Bh4",
      "g3",
      "f4",
      "gxf4",
      "exf4",
      "Bf2",
      "Bf6",
      "Qc2",
      "Qe5",
      "Kh1",
      "Qg5",
      "Rg1",
      "Ng3+",
      "Bxg3",
      "fxg3",
      "Rxg3",
      "Qh6",
      "Nb5",
      "Be5",
      "Rg2",
      "Rf7",
      "Nb3",
      "a6",
      "Nc3",
      "Rf4",
      "Qd2",
      "Qh4",
      "Nd1",
      "Bh3",
      "Rg1",
      "Bg4",
      "fxg4"
    ],
    "bestMove": "Qxh2+",
    "mistakeMove": "Bxb2",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_bronstein_bronstein-david-i_gufeld-eduard_77",
    "gameId": "famous-bronstein-david-i-gufeld-eduard-1961",
    "site": "https://lichess.org/analysis/r4bk1/5p2/3p2p1/1K1Pp1P1/PPQ1P3/8/3BNq2/8_b_-_-_0_39",
    "player": "Eduard Gufeld",
    "opponent": "David I Bronstein",
    "eco": "E85",
    "date": "1961",
    "abdulsColor": "black",
    "setupMoves": [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "f3",
      "O-O",
      "Be3",
      "e5",
      "Nge2",
      "Nbd7",
      "Qc2",
      "c6",
      "O-O-O",
      "Qe7",
      "g4",
      "a6",
      "d5",
      "cxd5",
      "cxd5",
      "b5",
      "Ng3",
      "Nc5",
      "b4",
      "Na4",
      "Nxa4",
      "bxa4",
      "g5",
      "Ne8",
      "h4",
      "Bd7",
      "Kb2",
      "Rc8",
      "Qd2",
      "Nc7",
      "h5",
      "Rb8",
      "Ka3",
      "Bb5",
      "Bh3",
      "Bd7",
      "Bf1",
      "Rb7",
      "Rc1",
      "Rfb8",
      "Rxc7",
      "Rxc7",
      "Bxa6",
      "Qe8",
      "Rc1",
      "Rxc1",
      "Qxc1",
      "Bb5",
      "Bxb5",
      "Qxb5",
      "Bd2",
      "Bf8",
      "Qc6",
      "Qd3+",
      "Qc3",
      "Qa6",
      "hxg6",
      "hxg6",
      "Qc6",
      "Qa7",
      "Ne2",
      "Qf2",
      "Qc4",
      "Qxf3+",
      "Kxa4",
      "Ra8+",
      "Kb5",
      "Qf2",
      "a4"
    ],
    "bestMove": "Rb8+",
    "mistakeMove": "Qxe2",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_keres_thomas-george-alan_keres-paul_45",
    "gameId": "famous-thomas-george-alan-keres-paul-1937",
    "site": "https://lichess.org/analysis/2krr3/1bp2pp1/p2P3p/1p6/6Nq/1P1P3n/1PQ2PPP/R1B2R1K_b_-_-_0_23",
    "player": "Paul Keres",
    "opponent": "George Alan Thomas",
    "eco": "C77",
    "date": "1937",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Ba4",
      "Nf6",
      "Nc3",
      "b5",
      "Bb3",
      "d6",
      "Ng5",
      "d5",
      "Nxd5",
      "Nd4",
      "Ne3",
      "Nxb3",
      "axb3",
      "h6",
      "Nf3",
      "Nxe4",
      "Nxe5",
      "Qf6",
      "Nf3",
      "Bb7",
      "Qe2",
      "O-O-O",
      "O-O",
      "Bd6",
      "Ng4",
      "Qf5",
      "d3",
      "Ng5",
      "Nh4",
      "Qd5",
      "c4",
      "Nh3+",
      "Kh1",
      "Qh5",
      "c5",
      "Rhe8",
      "Qc2",
      "Qxh4",
      "cxd6"
    ],
    "bestMove": "Bxg2+",
    "mistakeMove": "Qxg4",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_najdorf_larsen-bent_najdorf-miguel_73",
    "gameId": "famous-larsen-bent-najdorf-miguel-1968",
    "site": "https://lichess.org/analysis/8/6pk/pN5p/4Rp1q/4nP2/2r4P/Q5P1/6RK_b_-_-_0_37",
    "player": "Miguel Najdorf",
    "opponent": "Bent Larsen",
    "eco": "A03",
    "date": "1968",
    "abdulsColor": "black",
    "setupMoves": [
      "b3",
      "c5",
      "Bb2",
      "e6",
      "f4",
      "d5",
      "e3",
      "Nf6",
      "Nf3",
      "Be7",
      "Bb5+",
      "Bd7",
      "a4",
      "O-O",
      "O-O",
      "Nc6",
      "Qe2",
      "a6",
      "Bxc6",
      "Bxc6",
      "Ne5",
      "Rc8",
      "a5",
      "Nd7",
      "Nxc6",
      "Rxc6",
      "d3",
      "c4",
      "bxc4",
      "dxc4",
      "d4",
      "Nf6",
      "c3",
      "b5",
      "axb6",
      "Qxb6",
      "Ba3",
      "Bxa3",
      "Rxa3",
      "Nd5",
      "Re1",
      "Qb7",
      "Qc2",
      "Rb6",
      "Nd2",
      "Rb2",
      "Qc1",
      "Rb8",
      "Ra5",
      "f5",
      "h3",
      "h6",
      "Kh1",
      "Nf6",
      "Re5",
      "Ra2",
      "Rg1",
      "Qf7",
      "e4",
      "Rbb2",
      "Nxc4",
      "Rc2",
      "Qe3",
      "Nxe4",
      "d5",
      "exd5",
      "Nb6",
      "Rxc3",
      "Qd4",
      "Qh5",
      "Qxd5+",
      "Kh7",
      "Qxa2"
    ],
    "bestMove": "Rxh3+",
    "mistakeMove": "Qxh3+",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_geller_geller-efim-p_tukmakov-vladimir-b_68",
    "gameId": "famous-geller-efim-p-tukmakov-vladimir-b-1983",
    "site": "https://lichess.org/analysis/1Q1R4/5qpk/p3r2p/P4p2/3B3P/8/1P3P1K/5b2_w_-_-_7_35",
    "player": "Efim P Geller",
    "opponent": "Vladimir B Tukmakov",
    "eco": "B92",
    "date": "1983",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "c5",
      "Nf3",
      "d6",
      "d4",
      "cxd4",
      "Nxd4",
      "Nf6",
      "Nc3",
      "a6",
      "Be2",
      "e5",
      "Nb3",
      "Be7",
      "O-O",
      "O-O",
      "Be3",
      "Be6",
      "Qd2",
      "b5",
      "a4",
      "b4",
      "Nd5",
      "Nxe4",
      "Nxe7+",
      "Qxe7",
      "Qxb4",
      "f5",
      "Na5",
      "Rc8",
      "Bf3",
      "Bd5",
      "Rfd1",
      "Nc6",
      "Nxc6",
      "Bxc6",
      "a5",
      "Qf7",
      "c4",
      "d5",
      "cxd5",
      "Bxd5",
      "Bb6",
      "h6",
      "Qe1",
      "Rc2",
      "Rac1",
      "Rac8",
      "Be2",
      "Ng5",
      "Rxc2",
      "Rxc2",
      "h4",
      "Nh3+",
      "Kh2",
      "Nf4",
      "Bf1",
      "Bxg2",
      "Qxe5",
      "Bxf1",
      "Qxf4",
      "Rc4",
      "Rd8+",
      "Kh7",
      "Bd4",
      "Rc6",
      "Qb8",
      "Re6"
    ],
    "bestMove": "Rh8+",
    "mistakeMove": "Bxg7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_geller_geller-efim-p_cuellar-gacharna-miguel_79",
    "gameId": "famous-geller-efim-p-cuellar-gacharna-miguel-1962",
    "site": "https://lichess.org/analysis/3r4/8/6pk/p1Q4p/4B3/1P3PP1/P5KP/4q3_b_-_-_0_40",
    "player": "Miguel Cuellar Gacharna",
    "opponent": "Efim P Geller",
    "eco": "A49",
    "date": "1962",
    "abdulsColor": "black",
    "setupMoves": [
      "Nf3",
      "c5",
      "g3",
      "Nf6",
      "Bg2",
      "g6",
      "O-O",
      "Bg7",
      "d4",
      "O-O",
      "dxc5",
      "Na6",
      "Be3",
      "Ne4",
      "Bd4",
      "Bh6",
      "Ne5",
      "Nexc5",
      "Ng4",
      "Bg7",
      "Bxg7",
      "Kxg7",
      "Qd4+",
      "f6",
      "Nc3",
      "d6",
      "Qf4",
      "Bxg4",
      "Qxg4",
      "Qc8",
      "Qh4",
      "Nc7",
      "Rad1",
      "a5",
      "e4",
      "Ra6",
      "Rfe1",
      "b5",
      "Re3",
      "b4",
      "Nd5",
      "e6",
      "Nxc7",
      "Qxc7",
      "Bf1",
      "Raa8",
      "Qg4",
      "Rad8",
      "b3",
      "e5",
      "Rd2",
      "h5",
      "Qd1",
      "Ne6",
      "c3",
      "bxc3",
      "Rc2",
      "Qb7",
      "Bc4",
      "Nd4",
      "Bd5",
      "Qb4",
      "Rexc3",
      "Nxc2",
      "Rc7+",
      "Kh6",
      "Qxc2",
      "Qe1+",
      "Kg2",
      "f5",
      "exf5",
      "Rxf5",
      "f3",
      "e4",
      "Bxe4",
      "Rc5",
      "Rxc5",
      "dxc5",
      "Qxc5"
    ],
    "bestMove": "Rd2+",
    "mistakeMove": "Qxe4",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_smyslov_smyslov-vassily_mestel-a-jonathan_62",
    "gameId": "famous-smyslov-vassily-mestel-a-jonathan-1972",
    "site": "https://lichess.org/analysis/8/p1p5/b1qp3Q/6p1/P4k2/1P2R3/5K1P/8_w_-_-_2_32",
    "player": "Vassily Smyslov",
    "opponent": "A Jonathan Mestel",
    "eco": "A29",
    "date": "1972",
    "abdulsColor": "white",
    "setupMoves": [
      "c4",
      "Nf6",
      "Nc3",
      "e5",
      "Nf3",
      "Nc6",
      "g3",
      "Bb4",
      "Bg2",
      "O-O",
      "O-O",
      "Re8",
      "Nd5",
      "e4",
      "Ne1",
      "d6",
      "d3",
      "Bxe1",
      "Rxe1",
      "exd3",
      "Bg5",
      "dxe2",
      "Rxe2",
      "Rxe2",
      "Qxe2",
      "Be6",
      "Nxf6+",
      "gxf6",
      "Bh4",
      "Ne5",
      "Bxb7",
      "Bxc4",
      "Qh5",
      "Rb8",
      "Be4",
      "Ng6",
      "b3",
      "Ba6",
      "Re1",
      "Rb5",
      "Bd5",
      "Kg7",
      "a4",
      "Rb4",
      "Bxf7",
      "Qd7",
      "Bxg6",
      "hxg6",
      "Bxf6+",
      "Kxf6",
      "Qh8+",
      "Kg5",
      "f4+",
      "Kg4",
      "Re3",
      "g5",
      "Qh6",
      "Rxf4",
      "gxf4",
      "Kxf4",
      "Kf2",
      "Qc6"
    ],
    "bestMove": "Qf6+",
    "mistakeMove": "Qxg5+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_botvinnik_dobropistsev-j_botvinnik-mikhail_85",
    "gameId": "famous-dobropistsev-j-botvinnik-mikhail-1926",
    "site": "https://lichess.org/analysis/8/6kp/p4rp1/3PQ3/1p2PPK1/1P6/2B3R1/4q2r_b_-_-_6_43",
    "player": "Mikhail Botvinnik",
    "opponent": "J. Dobropistsev",
    "eco": "C98",
    "date": "1926",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nc6",
      "Bb5",
      "a6",
      "Ba4",
      "Nf6",
      "O-O",
      "Be7",
      "Re1",
      "b5",
      "Bb3",
      "O-O",
      "c3",
      "d6",
      "h3",
      "Na5",
      "Bc2",
      "c5",
      "d4",
      "Qc7",
      "Nbd2",
      "Nc6",
      "d5",
      "Nd8",
      "Nf1",
      "c4",
      "N3h2",
      "Nb7",
      "f4",
      "exf4",
      "Bxf4",
      "Nd7",
      "Qh5",
      "Ne5",
      "Re3",
      "Bf6",
      "Ng4",
      "Bxg4",
      "hxg4",
      "g6",
      "Qh3",
      "Nc5",
      "g5",
      "Bh8",
      "Nh2",
      "Ncd3",
      "Bxe5",
      "Nxe5",
      "Ng4",
      "Nxg4",
      "Qxg4",
      "Qc5",
      "Re1",
      "b4",
      "Qh4",
      "Ra7",
      "Kh1",
      "f6",
      "b3",
      "fxg5",
      "Qxg5",
      "Bxc3",
      "R1e2",
      "Rf1+",
      "Kh2",
      "Be5+",
      "g3",
      "Raf7",
      "Rg2",
      "cxb3",
      "axb3",
      "Bf4",
      "gxf4",
      "Qxe3",
      "Qd8+",
      "Kg7",
      "Qxd6",
      "Qe1",
      "Qe5+",
      "Rf6",
      "Kh3",
      "Rh1+",
      "Kg4"
    ],
    "bestMove": "Rh4+",
    "mistakeMove": "Qxe4",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_euwe_euwe-max_lohr-s_44",
    "gameId": "famous-euwe-max-lohr-s-1923",
    "site": "https://lichess.org/analysis/1rbk1r2/pp4R1/3Np3/3p2p1/6q1/BP2P3/P2P2B1/2R3K1_w_-_-_3_23",
    "player": "Max Euwe",
    "opponent": "S. Lohr",
    "eco": "A11",
    "date": "1923",
    "abdulsColor": "white",
    "setupMoves": [
      "Nf3",
      "Nf6",
      "c4",
      "g6",
      "g3",
      "Bg7",
      "Bg2",
      "c6",
      "O-O",
      "d5",
      "Ne5",
      "Nbd7",
      "f4",
      "h5",
      "cxd5",
      "cxd5",
      "Nc3",
      "e6",
      "b3",
      "h4",
      "Ba3",
      "hxg3",
      "hxg3",
      "Nxe5",
      "fxe5",
      "Ng4",
      "e3",
      "Qg5",
      "Rf4",
      "Nxe5",
      "Nb5",
      "Qxg3",
      "Qe2",
      "g5",
      "Nd6+",
      "Kd8",
      "Rxf7",
      "Ng4",
      "Qxg4",
      "Qxg4",
      "Rxg7",
      "Rf8",
      "Rc1",
      "Rb8"
    ],
    "bestMove": "Rxc8+",
    "mistakeMove": "Nxc8",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_janowski_mieses-jacques_janowsky-dawid-markelowicz_60",
    "gameId": "famous-mieses-jacques-janowsky-dawid-markelowicz-1895",
    "site": "https://lichess.org/analysis/2r1q3/1p1b1kp1/p1pp1B2/3Pp3/4B2Q/2PP4/PP4K1/7R_w_-_-_1_31",
    "player": "Jacques Mieses",
    "opponent": "Dawid Markelowicz Janowsky",
    "eco": "C26",
    "date": "1895",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "g3",
      "Nf6",
      "Bg2",
      "Bc5",
      "d3",
      "a6",
      "Nge2",
      "d6",
      "h3",
      "h6",
      "O-O",
      "Bd7",
      "Nd5",
      "Nxd5",
      "exd5",
      "Nd4",
      "Nxd4",
      "Bxd4",
      "c3",
      "Bb6",
      "Kh2",
      "Qe7",
      "Qe2",
      "O-O",
      "f4",
      "Rae8",
      "f5",
      "f6",
      "h4",
      "Rc8",
      "g4",
      "Kf7",
      "g5",
      "hxg5",
      "Qh5+",
      "Kg8",
      "hxg5",
      "fxg5",
      "Be4",
      "Qe8",
      "Qg4",
      "Kf7",
      "Bxg5",
      "Rh8+",
      "Kg2",
      "Kg8",
      "Rh1",
      "Rxh1",
      "Rxh1",
      "c6",
      "Qh4",
      "Bd8",
      "f6",
      "Bxf6",
      "Bxf6",
      "Kf7"
    ],
    "bestMove": "Bg6+",
    "mistakeMove": "Bxg7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_janowski_mieses-jacques_janowsky-dawid-markelowicz_65",
    "gameId": "famous-mieses-jacques-janowsky-dawid-markelowicz-1895",
    "site": "https://lichess.org/analysis/5k2/pp3p2/2p3n1/2p2Q2/2B3P1/3P2rq/PPP2K2/5R2_b_-_-_8_33",
    "player": "Dawid Markelowicz Janowsky",
    "opponent": "Jacques Mieses",
    "eco": "C28",
    "date": "1895",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "Bc4",
      "Nf6",
      "d3",
      "Bc5",
      "Bg5",
      "h6",
      "Bh4",
      "d6",
      "Qd2",
      "Nxe4",
      "Nxe4",
      "Qxh4",
      "Nxc5",
      "dxc5",
      "Nf3",
      "Qe7",
      "O-O",
      "Bg4",
      "Nxe5",
      "Nxe5",
      "Rae1",
      "O-O",
      "Qf4",
      "Rae8",
      "Re4",
      "Qf6",
      "Qg3",
      "Bf5",
      "Rf4",
      "g5",
      "h4",
      "Ng6",
      "hxg5",
      "hxg5",
      "Rf3",
      "Re5",
      "Re3",
      "Rfe8",
      "Rxe5",
      "Rxe5",
      "f4",
      "gxf4",
      "Rxf4",
      "Kf8",
      "Rf1",
      "Qh4",
      "Qf3",
      "c6",
      "g4",
      "Qg5",
      "Kh1",
      "Re3",
      "Qxf5",
      "Qh4+",
      "Kg1",
      "Qg3+",
      "Kh1",
      "Qh3+",
      "Kg1",
      "Rg3+",
      "Kf2"
    ],
    "bestMove": "Rg2+",
    "mistakeMove": "Qxf1+",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_schlechter_wolf-heinrich_schlechter-carl_55",
    "gameId": "famous-wolf-heinrich-schlechter-carl-1904",
    "site": "https://lichess.org/analysis/7B/p1Qnkp1p/2Br4/8/P1P2pp1/4q2P/1P3nP1/R5K1_b_-_-_3_28",
    "player": "Carl Schlechter",
    "opponent": "Heinrich Wolf",
    "eco": "C30",
    "date": "1904",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "f4",
      "Bc5",
      "Nf3",
      "d6",
      "Nc3",
      "Bg4",
      "Na4",
      "exf4",
      "c3",
      "Qf6",
      "e5",
      "Qh6",
      "d4",
      "Bb6",
      "Bc4",
      "Nd7",
      "exd6",
      "O-O-O",
      "O-O",
      "Qxd6",
      "Nxb6+",
      "Nxb6",
      "Be2",
      "Bxf3",
      "Bxf3",
      "g5",
      "a4",
      "Nf6",
      "Qb3",
      "Nbd5",
      "c4",
      "Nb4",
      "Bd2",
      "Qxd4+",
      "Rf2",
      "Nd3",
      "Qxb7+",
      "Kd7",
      "Qc6+",
      "Ke7",
      "Bc3",
      "Qxf2+",
      "Kh1",
      "Rd6",
      "Qxc7+",
      "Nd7",
      "Bxh8",
      "Qe3",
      "h3",
      "g4",
      "Bc6",
      "Nf2+",
      "Kg1"
    ],
    "bestMove": "Nd1+",
    "mistakeMove": "Rxc6",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_teichmann_burn-amos_teichmann-richard_53",
    "gameId": "famous-burn-amos-teichmann-richard-1895",
    "site": "https://lichess.org/analysis/4r1k1/pp1b2pp/2p2r2/2PpB3/1P3p2/4PP2/P1B1QP1K/3R2R1_b_-_-_0_27",
    "player": "Richard Teichmann",
    "opponent": "Amos Burn",
    "eco": "D46",
    "date": "1895",
    "abdulsColor": "black",
    "setupMoves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "Nf3",
      "c6",
      "e3",
      "Bd6",
      "Bd3",
      "Nbd7",
      "c5",
      "Bc7",
      "b4",
      "e5",
      "dxe5",
      "Nxe5",
      "Nxe5",
      "Bxe5",
      "Bb2",
      "Qe7",
      "Be2",
      "O-O",
      "Qc2",
      "Bd7",
      "O-O",
      "Rae8",
      "Rad1",
      "Bb8",
      "Nb1",
      "Ne4",
      "Nd2",
      "f5",
      "Bd4",
      "Ng5",
      "Bd3",
      "f4",
      "Kh1",
      "Qf7",
      "Nf3",
      "Nxf3",
      "gxf3",
      "Qh5",
      "Rg1",
      "Rf7",
      "Qe2",
      "Be5",
      "Bc2",
      "Rf6",
      "Bxe5",
      "Qxh2+",
      "Kxh2"
    ],
    "bestMove": "Rh6+",
    "mistakeMove": "Rxe5",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 10,
    "type": "blunder"
  },
  {
    "id": "famous_tal_tal-mihail_rantanen-yrjo-a_56",
    "gameId": "famous-tal-mihail-rantanen-yrjo-a-1979",
    "site": "https://lichess.org/analysis/1rq1r2B/5k1p/p2p1p2/2p1p3/2P1P2Q/1P6/P5PP/3b2K1_w_-_-_0_29",
    "player": "Mihail Tal",
    "opponent": "Yrjo A Rantanen",
    "eco": "B30",
    "date": "1979",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "c5",
      "Nf3",
      "Nc6",
      "Bb5",
      "e6",
      "O-O",
      "Nge7",
      "Nc3",
      "a6",
      "Bxc6",
      "Nxc6",
      "d4",
      "cxd4",
      "Nxd4",
      "d6",
      "Re1",
      "Bd7",
      "Nxc6",
      "bxc6",
      "Qg4",
      "e5",
      "Qg3",
      "f6",
      "Be3",
      "Kf7",
      "Rad1",
      "Be7",
      "Na4",
      "Rb8",
      "b3",
      "Re8",
      "c4",
      "c5",
      "Nc3",
      "Bf8",
      "f4",
      "Kg8",
      "Rf1",
      "Qc8",
      "fxe5",
      "fxe5",
      "Nd5",
      "Kh8",
      "Rf7",
      "Bg4",
      "Nf6",
      "gxf6",
      "Qh4",
      "Bg7",
      "Bh6",
      "Bxd1",
      "Bxg7+",
      "Kg8",
      "Bh8",
      "Kxf7"
    ],
    "bestMove": "Qxf6+",
    "mistakeMove": "Bxf6",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 8,
    "type": "blunder"
  },
  {
    "id": "famous_tal_tal-mihail_sveshnikov-evgeny_70",
    "gameId": "famous-tal-mihail-sveshnikov-evgeny-1990",
    "site": "https://lichess.org/analysis/3R4/p4r1p/1p2bNpk/1n6/6Q1/6P1/P4PKP/2q5_w_-_-_0_36",
    "player": "Mihail Tal",
    "opponent": "Evgeny Sveshnikov",
    "eco": "B10",
    "date": "1990",
    "abdulsColor": "white",
    "setupMoves": [
      "c4",
      "c6",
      "e4",
      "d5",
      "cxd5",
      "cxd5",
      "exd5",
      "Nf6",
      "Nc3",
      "g6",
      "Qb3",
      "Bg7",
      "g3",
      "b6",
      "Bg2",
      "Bb7",
      "Nge2",
      "e6",
      "Nf4",
      "e5",
      "Nfe2",
      "O-O",
      "O-O",
      "Na6",
      "d4",
      "exd4",
      "Nxd4",
      "Nc5",
      "Qc4",
      "Rc8",
      "Nc6",
      "Qd7",
      "Qh4",
      "Kh8",
      "Bh3",
      "Qe8",
      "Bxc8",
      "Qxc8",
      "Bh6",
      "Nxd5",
      "Nxd5",
      "Qxc6",
      "Bxg7+",
      "Kxg7",
      "Rad1",
      "f6",
      "Rfe1",
      "Rf7",
      "b4",
      "Ne6",
      "Qg4",
      "Nc7",
      "b5",
      "Nxb5",
      "Re6",
      "Qc5",
      "Nf4",
      "Bc8",
      "Rd5",
      "Qc1+",
      "Rd1",
      "Qc5",
      "Rd8",
      "Qc7",
      "Nh5+",
      "Kh6",
      "Nxf6",
      "Qc1+",
      "Kg2",
      "Bxe6"
    ],
    "bestMove": "Qh4+",
    "mistakeMove": "Qxe6",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 8,
    "type": "blunder"
  },
  {
    "id": "famous_capablanca_capablanca-jose-raul_marshall-frank-james_82",
    "gameId": "famous-capablanca-jose-raul-marshall-frank-james-1910",
    "site": "https://lichess.org/analysis/8/6R1/1p5k/2b3R1/4KP1p/6P1/P4r1P/8_w_-_-_0_42",
    "player": "Jose Raul Capablanca",
    "opponent": "Frank James Marshall",
    "eco": "C42",
    "date": "1910",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nxe5",
      "d6",
      "Nf3",
      "Nxe4",
      "d4",
      "d5",
      "Bd3",
      "Bg4",
      "O-O",
      "Nc6",
      "Re1",
      "f5",
      "c4",
      "Bd6",
      "cxd5",
      "Bxf3",
      "Qxf3",
      "Nxd4",
      "Qe3",
      "Qf6",
      "Bxe4",
      "fxe4",
      "Qxe4+",
      "Kf7",
      "Bg5",
      "Qxg5",
      "Qxd4",
      "Rhe8",
      "Nc3",
      "Kg8",
      "Ne4",
      "Qh6",
      "g3",
      "Rad8",
      "Qxa7",
      "Bb4",
      "Re3",
      "b6",
      "Qxc7",
      "Rc8",
      "Qd7",
      "Qg6",
      "d6",
      "Rcd8",
      "Qc7",
      "Rc8",
      "d7",
      "Rxc7",
      "dxe8=Q+",
      "Qxe8",
      "Nf6+",
      "gxf6",
      "Rxe8+",
      "Kf7",
      "Re2",
      "Rc4",
      "Rd1",
      "Bc5",
      "Kg2",
      "Kg6",
      "f4",
      "h5",
      "Kf3",
      "f5",
      "Re6+",
      "Kf7",
      "Re5",
      "Rc2",
      "Rxf5+",
      "Kg6",
      "Rg5+",
      "Kh6",
      "Rd7",
      "Rxb2",
      "Rdg7",
      "Rf2+",
      "Ke4",
      "h4"
    ],
    "bestMove": "R5g6+",
    "mistakeMove": "Rxc5",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 8,
    "type": "blunder"
  },
  {
    "id": "famous_alekhine_alekhine-alexander_stephan-anna_38",
    "gameId": "famous-alekhine-alexander-stephan-anna-1925",
    "site": "https://lichess.org/analysis/r1b2r1k/pp4pp/3P4/4qp2/2B1nN2/5R2/PP1Q2PP/R5K1_w_-_-_1_20",
    "player": "Alexander Alekhine",
    "opponent": "Anna Stephan",
    "eco": "D06",
    "date": "1925",
    "abdulsColor": "white",
    "setupMoves": [
      "d4",
      "d5",
      "c4",
      "Nf6",
      "cxd5",
      "Nxd5",
      "e4",
      "Nb6",
      "Nc3",
      "e5",
      "d5",
      "Bb4",
      "Bd3",
      "O-O",
      "Ne2",
      "c6",
      "O-O",
      "cxd5",
      "Nxd5",
      "Nxd5",
      "exd5",
      "Nd7",
      "f4",
      "exf4",
      "Nxf4",
      "Qc7",
      "Be3",
      "Qe5",
      "Rf3",
      "Bc5",
      "Bxc5",
      "Nxc5",
      "Qd2",
      "f5",
      "Bc4",
      "Ne4",
      "d6+",
      "Kh8"
    ],
    "bestMove": "Ng6+",
    "mistakeMove": "d7",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 8,
    "type": "blunder"
  },
  {
    "id": "famous_fischer_greenblatt-programm_fischer-robert-james_75",
    "gameId": "famous-greenblatt-programm-fischer-robert-james-1977",
    "site": "https://lichess.org/analysis/6k1/3Q2p1/3n4/4p3/8/2Pq2P1/PP1Nbr2/R1K5_b_-_-_0_38",
    "player": "Robert James Fischer",
    "opponent": "Greenblatt Programm",
    "eco": "B92",
    "date": "1977",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "c5",
      "Nf3",
      "d6",
      "d4",
      "cxd4",
      "Nxd4",
      "Nf6",
      "Nc3",
      "a6",
      "Be2",
      "e5",
      "Nb3",
      "Be7",
      "Be3",
      "O-O",
      "Qd3",
      "Be6",
      "O-O",
      "Nbd7",
      "Nd5",
      "Rc8",
      "Nxe7+",
      "Qxe7",
      "f3",
      "d5",
      "Nd2",
      "Qb4",
      "Nb3",
      "dxe4",
      "Qd1",
      "Nd5",
      "Ba7",
      "b6",
      "c3",
      "Qe7",
      "fxe4",
      "Ne3",
      "Qd3",
      "Nxf1",
      "Qxa6",
      "Ne3",
      "Bxb6",
      "Qg5",
      "g3",
      "Ra8",
      "Ba7",
      "h5",
      "Qb7",
      "h4",
      "Kf2",
      "hxg3+",
      "hxg3",
      "f5",
      "exf5",
      "Rxf5+",
      "Ke1",
      "Raf8",
      "Kd2",
      "Nc4+",
      "Kc2",
      "Qg6",
      "Qe4",
      "Nd6",
      "Qc6",
      "Rf2+",
      "Kd1",
      "Bg4",
      "Bxf2",
      "Qd3+",
      "Kc1",
      "Bxe2",
      "Nd2",
      "Rxf2",
      "Qxd7"
    ],
    "bestMove": "Rf1+",
    "mistakeMove": "Qxd2+",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 8,
    "type": "blunder"
  },
  {
    "id": "famous_fischer_fischer-robert-james_bennett-j1_76",
    "gameId": "famous-fischer-robert-james-bennett-j1-1957",
    "site": "https://lichess.org/analysis/3q3k/p6p/6p1/5p2/5P1P/1Bb2QP1/Pr6/6K1_w_-_-_0_39",
    "player": "Robert James Fischer",
    "opponent": "J1. Bennett",
    "eco": "B60",
    "date": "1957",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "c5",
      "Nf3",
      "Nc6",
      "d4",
      "cxd4",
      "Nxd4",
      "Nf6",
      "Nc3",
      "d6",
      "Bg5",
      "g6",
      "Bxf6",
      "exf6",
      "Bc4",
      "Bg7",
      "O-O",
      "O-O",
      "Ndb5",
      "f5",
      "exf5",
      "Bxf5",
      "Nxd6",
      "Ne5",
      "Bb3",
      "Qd7",
      "Nxf5",
      "Qxf5",
      "Nd5",
      "Nc6",
      "Ne3",
      "Qc5",
      "c3",
      "Rad8",
      "Qf3",
      "Rd7",
      "Rad1",
      "Rd6",
      "Rxd6",
      "Qxd6",
      "Rd1",
      "Qc5",
      "h3",
      "b5",
      "Rd5",
      "Qb6",
      "Rd6",
      "Ne5",
      "Qd5",
      "Qc7",
      "f4",
      "Nc4",
      "Nxc4",
      "bxc4",
      "Bxc4",
      "Kh8",
      "Bb3",
      "f5",
      "g3",
      "Re8",
      "Qc6",
      "Qb8",
      "Rd7",
      "Re1+",
      "Kf2",
      "Qe8",
      "Qf3",
      "Rb1",
      "Rd1",
      "Rxb2+",
      "Kg1",
      "Qc8",
      "h4",
      "Bxc3",
      "Rd8+",
      "Qxd8"
    ],
    "bestMove": "Qxc3+",
    "mistakeMove": "h5",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 8,
    "type": "blunder"
  },
  {
    "id": "famous_marshall_didier-m1_marshall-frank-james_49",
    "gameId": "famous-didier-m1-marshall-frank-james-1900",
    "site": "https://lichess.org/analysis/3rr1k1/ppb2pp1/2p3b1/3q4/2BP2Q1/1PP2p1P/P2B1P2/R4KR1_b_-_-_0_25",
    "player": "Frank James Marshall",
    "opponent": "M1. Didier",
    "eco": "C42",
    "date": "1900",
    "abdulsColor": "black",
    "setupMoves": [
      "e4",
      "e5",
      "Nf3",
      "Nf6",
      "Nc3",
      "Bb4",
      "Bc4",
      "O-O",
      "d3",
      "d5",
      "exd5",
      "Nxd5",
      "Bd2",
      "Nf4",
      "O-O",
      "Bg4",
      "h3",
      "Bh5",
      "Kh2",
      "Nc6",
      "g4",
      "Bg6",
      "Ne2",
      "Bd6",
      "Nxf4",
      "exf4",
      "Rh1",
      "h5",
      "Kg1",
      "Ne5",
      "Nxe5",
      "Bxe5",
      "Qf3",
      "Qg5",
      "Kf1",
      "Rfe8",
      "c3",
      "Rad8",
      "Rg1",
      "c6",
      "d4",
      "Bc7",
      "gxh5",
      "Qxh5",
      "Qg2",
      "f3",
      "Qg4",
      "Qd5",
      "b3"
    ],
    "bestMove": "Qxc4+",
    "mistakeMove": "Qxd4",
    "evalBefore": -99,
    "evalAfter": -1,
    "drop": 8,
    "type": "blunder"
  },
  {
    "id": "famous_marshall_marshall-frank-james_mason-james_84",
    "gameId": "famous-marshall-frank-james-mason-james-1902",
    "site": "https://lichess.org/analysis/3B2Q1/1p6/2p5/6rp/p6k/5q1P/P4P2/3R1K2_w_-_-_0_43",
    "player": "Frank James Marshall",
    "opponent": "James Mason",
    "eco": "D52",
    "date": "1902",
    "abdulsColor": "white",
    "setupMoves": [
      "d4",
      "d5",
      "c4",
      "e6",
      "Nc3",
      "Nf6",
      "Bg5",
      "Be7",
      "e3",
      "Nbd7",
      "Nf3",
      "c6",
      "Bd3",
      "dxc4",
      "Bxc4",
      "Nd5",
      "Bxe7",
      "Qxe7",
      "O-O",
      "Nxc3",
      "bxc3",
      "e5",
      "e4",
      "O-O",
      "Re1",
      "exd4",
      "cxd4",
      "Nf6",
      "h3",
      "g6",
      "Qd2",
      "Kg7",
      "Qb2",
      "h6",
      "Rad1",
      "a5",
      "Ne5",
      "Qb4",
      "Qc1",
      "a4",
      "Re3",
      "Qe7",
      "Qc3",
      "Kh7",
      "Bxf7",
      "Rxf7",
      "Nxf7",
      "Qxf7",
      "Rf3",
      "Qe7",
      "d5",
      "Nxe4",
      "d6",
      "Qe6",
      "Qd3",
      "Nc5",
      "Qc2",
      "Nd7",
      "Re3",
      "Qf6",
      "Re7+",
      "Kh8",
      "Re8+",
      "Kh7",
      "Qc4",
      "h5",
      "Qg8+",
      "Kh6",
      "Rxc8",
      "Ra5",
      "Rc7",
      "Ne5",
      "Rh7+",
      "Kg5",
      "d7",
      "Nf3+",
      "gxf3",
      "Kh4",
      "d8=B",
      "Rg5+",
      "Kf1",
      "Qxf3",
      "Rxh5+",
      "gxh5"
    ],
    "bestMove": "Qxg5+",
    "mistakeMove": "Bxg5+",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 8,
    "type": "blunder"
  },
  {
    "id": "famous_pillsbury_pillsbury-harry-nelson_fernandez_14",
    "gameId": "famous-pillsbury-harry-nelson-fernandez-1900",
    "site": "https://lichess.org/analysis/r2qkbnr/1pp2ppp/p2p4/4N3/2B1P3/2N5/PPPP2PP/R1BbK2R_w_KQkq_-_0_8",
    "player": "Harry Nelson Pillsbury",
    "opponent": "Fernandez",
    "eco": "C25",
    "date": "1900",
    "abdulsColor": "white",
    "setupMoves": [
      "e4",
      "e5",
      "Nc3",
      "Nc6",
      "f4",
      "d6",
      "Nf3",
      "a6",
      "Bc4",
      "Bg4",
      "fxe5",
      "Nxe5",
      "Nxe5",
      "Bxd1"
    ],
    "bestMove": "Bxf7+",
    "mistakeMove": "Nxd1",
    "evalBefore": 99,
    "evalAfter": 1,
    "drop": 8,
    "type": "blunder"
  }
];
